Update

diff --git a/broker b/broker
--- a/broker
+++ b/broker
@@ -400,6 +400,7 @@ $(listOrders | jq -r '.[] | "\(.Code): \(.Type) \(.Amount) \(.OriginalAmount) \(
 
   OPTIONS=(1 "Dashbord         Strategy status"
     i "Indicators       Current conditions"
+    c "Config           Configurations"
     2 "Create           Create strategy"
     3 "Control          Robot controller"
     5 "Logs             robot.log")
@@ -469,6 +470,43 @@ $(get_ema 50 200 "$COIN_TOKEN")" >"${LOG_DIR:?}"/leeloo/indicators/ema_indicator
       RESULT="$(cat "${LOG_DIR:?}"/leeloo/indicators/ema_indicators 2>/dev/null)"
       display_result 2>/dev/null
     fi
+
+    ;;
+
+  "c")
+
+    # Find all config files in the directory
+    CONFIG_FILES=(/usr/local/bin/include/leeloo/robot/*.config)
+
+    # Count the number of config files found
+    NUM_FILES="${#CONFIG_FILES[@]}"
+
+    # Check if any config files were found
+    if [ $NUM_FILES -eq 0 ] &>/dev/null; then
+      echo "Error: No config files found in $SYS_DIR/robot"
+      exit 1
+    fi
+
+    # Create an array of options with line numbers
+    OPTIONS=()
+    for ((i = 0; i < "$NUM_FILES"; i++)); do
+      OPTIONS+=("$((i + 1))" "${CONFIG_FILES[$i]}")
+    done
+
+    # Use --menu to display the options and get the user's selection
+    while true; do
+      CHOICE=$(dialog --clear --title "Select a config file" --menu "Choose one of the following config files:" "$(echo "$NUM_FILES+4" | bc)" 0 0 "${OPTIONS[@]}" 2>&1 >/dev/tty)
+      if [ $? -eq 0 ] &>/dev/null; then
+        # User made a selection
+        SELECTED_FILE="${CONFIG_FILES[$((CHOICE - 1))]}"
+        nano "$SELECTED_FILE"
+        break
+      else
+        # User cancelled
+        echo "You cancelled"
+        exit 1
+      fi
+    done
 
     ;;
 
