Update

diff --git a/broker b/broker
--- a/broker
+++ b/broker
@@ -377,9 +377,9 @@ $(cat "${LOG_DIR:?}"/leeloo/southxchange/orders 2>/dev/null | sort -r)"
 
 "A")
 
-  HEIGHT=14
+  HEIGHT=15
   WIDTH=47
-  CHOICE_HEIGHT=8
+  CHOICE_HEIGHT=9
   BACKTITLE="Leeloo (Multipass)"
   TITLE="Strategy Menu"
   MENU="Multipass $(date | xargs)"
@@ -390,7 +390,8 @@ $(cat "${LOG_DIR:?}"/leeloo/southxchange/orders 2>/dev/null | sort -r)"
     4 "Config           Configurations"
     5 "Create           Create strategy"
     6 "Control          Robot controller"
-    7 "Logs             robot.log")
+    7 "Logs             robot.log"
+    0 "Delete           Remove strategy")
 
   CHOICE=$(dialog --clear \
     --backtitle "$BACKTITLE" \
@@ -527,7 +528,7 @@ $(cat "${LOG_DIR:?}"/leeloo/robot.hodl 2>/dev/null)" | column -t)" >"${LOG_DIR:?
   "4")
 
     while true; do
-      CONFIG_FILES=(/usr/local/bin/include/leeloo/robot/*.config)
+      CONFIG_FILES=("${SYS_DIR:?}"/robot/*.config)
       NUM_FILES="${#CONFIG_FILES[@]}"
       WIDTH="$(echo "$(wc -L "${CONFIG_FILES:?}" | awk '{ print $1 }')+3" | bc 2>/dev/null)"
 
@@ -791,6 +792,36 @@ $(ls -lSah "${SYS_DIR:?}"/robot* 2>/dev/null | column -t)"
   "7")
 
     last_log_robot
+
+    ;;
+
+  "0")
+
+    while true; do
+      CONFIG_FILES=("${SYS_DIR:?}"/robot/*.config)
+      NUM_FILES="${#CONFIG_FILES[@]}"
+      WIDTH="$(echo "$(wc -L "${CONFIG_FILES:?}" | awk '{ print $1 }')+3" | bc 2>/dev/null)"
+
+      if [ $NUM_FILES -eq 0 ] &>/dev/null; then
+        echo "Error: No config files found in $SYS_DIR/robot"
+        exit 1
+      fi
+
+      OPTIONS=()
+      for ((i = 0; i < "$NUM_FILES"; i++)); do
+        OPTIONS+=("$((i + 1))" "${CONFIG_FILES[$i]}")
+      done
+
+      CHOICE=$(dialog --clear --title "Delete Strategy Menu" --menu "Choose one of the following strategy configurations:" "$(echo "$NUM_FILES+4" | bc)" "$WIDTH" 0 "${OPTIONS[@]}" 2>&1 >/dev/tty)
+
+      if [ -n "$CHOICE" ]; then
+        SELECTED_FILE="${CONFIG_FILES[$((CHOICE - 1))]}"
+        rm "$SELECTED_FILE"
+        break
+      else
+        break
+      fi
+    done
 
     ;;
 
