Update

diff --git a/broker b/broker
--- a/broker
+++ b/broker
@@ -1276,28 +1276,34 @@ $STRATEGY_ERROR"
 
   ##############################################################################
 
-  if dialog --stdout --title "Check data?" \
-    --backtitle "Check data?" \
-    --yesno "Yes: Check!, No:  Go back!" 5 32; then
-    # leeloo data exist, edit
-    if [[ "$LEELOO_DATA" -gt "0" ]] &>/dev/null; then
-      nano "$LOG_DIR"/leeloo/leeloo.log
-      clear
-      if ! dialog --stdout --title "Keep data?" \
-        --backtitle "Keep data?" \
-        --yesno "Yes: Keep!, No:  Go Delete!" 5 32; then
-        truncate -s 0 "$LOG_DIR"/leeloo/leeloo.log &>/dev/null
-      fi
-    fi
+  DEBUG_DATA="$(echo "$LEELOO_DATA+$STRATEGY_DATA" | bc 2>/dev/null)"
 
-    # strategy data exist, edit
-    if [[ "$STRATEGY_DATA" -gt "0" ]] &>/dev/null; then
-      nano "$LOG_DIR"/leeloo/error.log
-      clear
-      if ! dialog --stdout --title "Keep data?" \
-        --backtitle "Keep data?" \
-        --yesno "Yes: Keep!, No:  Go Delete!" 5 32; then
-        truncate -s 0 "$LOG_DIR"/leeloo/error.log &>/dev/null
+  # data exist, check
+  if [[ "$DEBUG_DATA" -gt "0" ]] &>/dev/null; then
+    if dialog --stdout --title "Check data?" \
+      --backtitle "Check data?" \
+      --yesno "Yes: Check!, No:  Go back!" 5 32; then
+
+      # leeloo data exist, edit
+      if [[ "$LEELOO_DATA" -gt "0" ]] &>/dev/null; then
+        nano "$LOG_DIR"/leeloo/leeloo.log
+        clear
+        if ! dialog --stdout --title "Keep data?" \
+          --backtitle "Keep data?" \
+          --yesno "Yes: Keep!, No:  Go Delete!" 5 32; then
+          truncate -s 0 "$LOG_DIR"/leeloo/leeloo.log &>/dev/null
+        fi
+      fi
+
+      # strategy data exist, edit
+      if [[ "$STRATEGY_DATA" -gt "0" ]] &>/dev/null; then
+        nano "$LOG_DIR"/leeloo/error.log
+        clear
+        if ! dialog --stdout --title "Keep data?" \
+          --backtitle "Keep data?" \
+          --yesno "Yes: Keep!, No:  Go Delete!" 5 32; then
+          truncate -s 0 "$LOG_DIR"/leeloo/error.log &>/dev/null
+        fi
       fi
     fi
   fi
