Update

diff --git a/include/strategies/templates/xeggex b/include/strategies/templates/xeggex
--- a/include/strategies/templates/xeggex
+++ b/include/strategies/templates/xeggex
@@ -448,15 +448,21 @@ function target_order_status() {
 
     ############################################################################
 
+    # selling value
+    DIP_SELLING_VALUE="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY:?}"_"${REFERENCE_CURRENCY:?}".selling 2>/dev/null || true)"
+
     # if sold has data
     if [[ ! -z "$DIP_ORDER_SOLD_QUANTITY" && ! "$(echo "$DIP_ORDER_SOLD_QUANTITY" | tr -d '.' | sed 's/^0*//')" -eq "0" ]] &>/dev/null; then
       # if order is selling
       if [[ "$LAST_SELL_GROUP_ID" == "$LAST_SELL_ORDER_ID" ]] &>/dev/null; then
-        # track order amount being sold (update)
-        echo "$DIP_ORDER_SOLD_QUANTITY" | sed '/^$/d' >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY:?}"_"${REFERENCE_CURRENCY:?}".selling
-        # asset profit output (log)
-        DIP_SELL_ASSET_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Asset sold: +$DIP_ORDER_SOLD_QUANTITY $LISTING_CURRENCY Age: $DIP_BOUGHT_AGE_OUTPUT"
-        echo "$DIP_SELL_ASSET_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+        # if order value is unique
+        if [[ ! "$DIP_SELLING_VALUE" == "$DIP_ORDER_SOLD_QUANTITY" ]] &>/dev/null; then
+          # track order amount being sold (update)
+          echo "$DIP_ORDER_SOLD_QUANTITY" | sed '/^$/d' >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY:?}"_"${REFERENCE_CURRENCY:?}".selling
+          # asset profit output (log)
+          DIP_SELL_ASSET_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Asset sold: +$DIP_ORDER_SOLD_QUANTITY $LISTING_CURRENCY Age: $DIP_BOUGHT_AGE_OUTPUT"
+          echo "$DIP_SELL_ASSET_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+        fi
       fi
     fi
 
