Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -365,6 +365,7 @@ function target_data() {
 }
 
 ################################################################################
+
 function bought_sold_age() {
 
   # if not zero
@@ -1960,8 +1961,10 @@ $(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".gains 2>/dev/null)" >"$SYS_DIR"/
   truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".gains &>/dev/null
 
   # new year output (happy new year)
-  DIP_HAPPY_NEW_YEAR="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : ${DIP_OLD_YEAR:?} > ${DIP_NEW_YEAR:?} : Happy New Year?!"
-  echo "$DIP_HAPPY_NEW_YEAR" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"
+  if [[ "$(grep -c "Happy New Year" "${LOG_DIR:?}"/leeloo/robot.log || true)" -eq "0" ]] &>/dev/null; then
+    DIP_HAPPY_NEW_YEAR="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : ${DIP_OLD_YEAR:?} > ${DIP_NEW_YEAR:?} : Happy New Year?!"
+    echo "$DIP_HAPPY_NEW_YEAR" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"
+  fi
 fi
 
 ################################################################################
