Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -60,7 +60,9 @@ DIP_MAX_AGE="$(egrep "DIP_MAX_AGE=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".co
 # disregard other markets run by other bots
 DIP_DISREGARD_BOTS="$(egrep "DIP_DISREGARD_BOTS=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
 # max buy order age (days)
-DIP_OLD_ORDER_MAX="$(egrep "DIP_OLD_ORDER_MAX=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
+DIP_MAX_BUY_AGE="$(egrep "DIP_MAX_BUY_AGE=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
+# max sell order age (days)
+DIP_MAX_SELL_AGE="$(egrep "DIP_MAX_SELL_AGE=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
 
 ################################################################################
 # exchange template
@@ -1629,8 +1631,8 @@ if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | sed 
     # check age of sold file
     DIP_BS_STATUS_SOLD_AGE="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY:?}"_"${REFERENCE_CURRENCY:?}".sold 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
 
-    # if bought and sold are too old
-    if [[ "$DIP_BS_STATUS_BOUGHT_AGE" -gt "$(echo "$DIP_OLD_ORDER_MAX*86400" | bc 2>/dev/null)" && "$DIP_BS_STATUS_SOLD_AGE" -gt "$(echo "$DIP_OLD_ORDER_MAX*86400" | bc 2>/dev/null)" ]] &>/dev/null; then
+    # if bought and sold are too old (using max buy age limit on both)
+    if [[ "$DIP_BS_STATUS_BOUGHT_AGE" -gt "$(echo "$DIP_MAX_BUY_AGE*86400" | bc 2>/dev/null)" && "$DIP_BS_STATUS_SOLD_AGE" -gt "$(echo "$DIP_MAX_BUY_AGE*86400" | bc 2>/dev/null)" ]] &>/dev/null; then
       # reset sold file
       truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY:?}"_"${REFERENCE_CURRENCY:?}".sold &>/dev/null
       # if not zero
@@ -2075,54 +2077,93 @@ mv "${DIP_OUTPUT_FILE}.tmp" "$DIP_OUTPUT_FILE"
 echo "$(grep "$STRATEGY_TYPE" "${SYS_DIR:?}"/robot/pool)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".pool
 
 ################################################################################
-# removing old positions (single buys)
+# removing old positions (single buy orders)
 ################################################################################
 
 # if zero
-if [[ -z "$DIP_OLD_ORDER_MAX" ]] &>/dev/null; then
+if [[ -z "$DIP_MAX_BUY_AGE" ]] &>/dev/null; then
   # use default n days
-  DIP_OLD_ORDER_MAX="7"
+  DIP_MAX_BUY_AGE="7"
 fi
 
 # calculate days into seconds
-DIP_OLD_ORDER_MAX_SECONDS="$(echo "$DIP_OLD_ORDER_MAX*86400" | bc 2>/dev/null)"
+DIP_MAX_BUY_AGE_SECONDS="$(echo "$DIP_MAX_BUY_AGE*86400" | bc 2>/dev/null)"
 
-# if older than n seconds
-if [[ "$DIP_BOUGHT_FILE_AGE_SECONDS" -gt "$DIP_OLD_ORDER_MAX_SECONDS" ]] &>/dev/null; then
-  if [[ "$DIP_SOLD_FILE_AGE_SECONDS" -gt "$DIP_OLD_ORDER_MAX_SECONDS" ]] &>/dev/null; then
+# if older than n seconds (using max buy age limit on both)
+if [[ "$DIP_BOUGHT_FILE_AGE_SECONDS" -gt "$DIP_MAX_BUY_AGE_SECONDS" ]] &>/dev/null; then
+  if [[ "$DIP_SOLD_FILE_AGE_SECONDS" -gt "$DIP_MAX_BUY_AGE_SECONDS" ]] &>/dev/null; then
     # if specific market exist in orders file (buy)
     if [[ "$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null | grep -w "$REFERENCE_CURRENCY" | grep -c "buy" || true)" -eq "1" ]] &>/dev/null; then
-
       # old order id (buy)
       DIP_ORDER_ID="$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders | grep -w "$REFERENCE_CURRENCY" | grep "buy" | awk '{ print $1 }' | tr -d ':')"
-
       # order id found
       if [[ -n "$DIP_ORDER_ID" ]] &>/dev/null; then
-
         # cancel old order (buy)
         cancelOrder "$DIP_ORDER_ID" 2>>"${LOG_ERROR:?}"
-
         sleep 1
         # remove old order
         echo "$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null | grep -v "$DIP_ORDER_ID")" >"${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders
-
         # if specific market dont exist in orders file (sell)
         if [[ "$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null | grep -w "$LISTING_CURRENCY" | grep -c "sell" || true)" -eq "0" ]] &>/dev/null; then
           # remove old (active) order (buy & sell does not exist)
           echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | grep -v "$LISTING_CURRENCY/$REFERENCE_CURRENCY")" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active
         fi
-
         log_date
-
         # order n greater than n
         if [[ "$(echo "$DIP_ORDER_ID" | wc -L)" -gt "9" ]] &>/dev/null; then
           DIP_ORDER_ID_DOTS=".."
         else
           DIP_ORDER_ID_DOTS=""
         fi
+        # removing buy order output (log)
+        DIP_ANCIENT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Removing buy order: ${DIP_ORDER_ID:0:9}$DIP_ORDER_ID_DOTS Age: $DIP_BOUGHT_AGE_OUTPUT (old) Spread: ${DIP_TARGET_SPREAD:?}%"
+        echo "$DIP_ANCIENT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+      fi
+    fi
+  fi
+fi
 
-        # removing output (log)
-        DIP_ANCIENT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Removing: ${DIP_ORDER_ID:0:9}$DIP_ORDER_ID_DOTS Age: $DIP_BOUGHT_AGE_OUTPUT (old) Spread: ${DIP_TARGET_SPREAD:?}%"
+################################################################################
+# removing old positions (single sell orders)
+################################################################################
+
+# if zero
+if [[ -z "$DIP_MAX_SELL_AGE" ]] &>/dev/null; then
+  # use default n days
+  DIP_MAX_SELL_AGE="14"
+fi
+
+# calculate days into seconds
+DIP_MAX_SELL_AGE_SECONDS="$(echo "$DIP_MAX_SELL_AGE*86400" | bc 2>/dev/null)"
+
+# if older than n seconds (using max sell age limit on both)
+if [[ "$DIP_BOUGHT_FILE_AGE_SECONDS" -gt "$DIP_MAX_SELL_AGE_SECONDS" ]] &>/dev/null; then
+  if [[ "$DIP_SOLD_FILE_AGE_SECONDS" -gt "$DIP_MAX_SELL_AGE_SECONDS" ]] &>/dev/null; then
+    # if specific market exist in orders file (sell)
+    if [[ "$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null | grep -w "$REFERENCE_CURRENCY" | grep -c "sell" || true)" -eq "1" ]] &>/dev/null; then
+      # old order id (sell)
+      DIP_ORDER_ID="$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders | grep -w "$REFERENCE_CURRENCY" | grep "sell" | awk '{ print $1 }' | tr -d ':')"
+      # order id found
+      if [[ -n "$DIP_ORDER_ID" ]] &>/dev/null; then
+        # cancel old order (sell)
+        cancelOrder "$DIP_ORDER_ID" 2>>"${LOG_ERROR:?}"
+        sleep 1
+        # remove old order
+        echo "$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null | grep -v "$DIP_ORDER_ID")" >"${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders
+        # if specific market dont exist in orders file (buy)
+        if [[ "$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null | grep -w "$LISTING_CURRENCY" | grep -c "buy" || true)" -eq "0" ]] &>/dev/null; then
+          # remove old (active) order (buy & sell does not exist)
+          echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | grep -v "$LISTING_CURRENCY/$REFERENCE_CURRENCY")" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active
+        fi
+        log_date
+        # order n greater than n
+        if [[ "$(echo "$DIP_ORDER_ID" | wc -L)" -gt "9" ]] &>/dev/null; then
+          DIP_ORDER_ID_DOTS=".."
+        else
+          DIP_ORDER_ID_DOTS=""
+        fi
+        # removing sell order output (log)
+        DIP_ANCIENT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Removing sell order: ${DIP_ORDER_ID:0:9}$DIP_ORDER_ID_DOTS Age: $DIP_BOUGHT_AGE_OUTPUT (old) Spread: ${DIP_TARGET_SPREAD:?}%"
         echo "$DIP_ANCIENT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
       fi
     fi
