Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -212,6 +212,26 @@ function cat_active_target() {
 # cat active, target data
 cat_active_target
 
+# market does not exist ########################################################
+
+# markets
+GHOST_MARKET="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".null 2>/dev/null | grep -c "Market Not Found" || true)"
+GHOST_TARGET="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".null 2>/dev/null | awk '{ print $7 }')"
+
+# if true
+if [[ "$GHOST_MARKET" -gt "0" ]] &>/dev/null; then
+  # if active order exist
+  if [[ "$(grep -c "$GHOST_TARGET" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active || true)" -gt "0" ]] &>/dev/null; then
+    # remove active order
+    echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | grep -v "$GHOST_TARGET")" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active
+    # log removing output
+    DIP_MARKET_GHOST="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : Ghost :: Market $GHOST_TARGET does not exist, removed!"
+    echo "$DIP_MARKET_GHOST" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+    # reset null
+    truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".null &>/dev/null
+  fi
+fi
+
 ################################################################################
 ################################################################################
 # specific target & specific active variables
@@ -239,6 +259,7 @@ function target_data() {
     ACTIVE_MARKETS=$(awk -F: '{ print $1 }' <<<"$CAT_ACTIVE_FILE")
     # initialize the variable to store missing markets
     MISSING_MARKETS=""
+
     # iterate through each line in ACTIVE_MARKETS
     while IFS= read -r ACTIVE_MARKET; do
       # check if the active market is not in the order markets
