Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -2038,6 +2038,9 @@ fi
 
 ################################################################################
 
+# default
+ERROR_STATUS=0
+
 # if profit found
 if [[ -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit ]] &>/dev/null; then
 
@@ -2092,6 +2095,9 @@ if [[ -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit ]] &>/dev/null; then
   # total gains by reference, remove duplicates, sort by n
   echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".gains 2>/dev/null | awk '!a[$1]++' | sort -n -k 3 | column -t)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".gains
 fi
+
+# exit with the error status (non-zero if errors occurred)
+exit $ERROR_STATUS
 
 ################################################################################
 
