Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -2696,73 +2696,80 @@ if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | sed 
       DIP_LEFTOVER_FILLED="0"
     fi
 
+    # sell + selling + filled (sold) - DIP_LEFTOVER_SIZE_OUTPUT + DIP_LEFTOVER_TOTAL + DIP_LEFTOVER_FILLED
+    DIP_LEFTOVER_TOTAL_CHECK="$(echo "${DIP_LEFTOVER_SIZE_OUTPUT:?}+${DIP_LEFTOVER_TOTAL:?}+${DIP_LEFTOVER_FILLED:?}" | bc -l 2>/dev/null | awk '{ printf "%.0f\n", $1 }')"
+
     ############################################################################
 
-    # amount of order filled (sold)
-    DIP_LEFTOVER_FILLED_AMOUNT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".selling 2>/dev/null | awk '{ SUM += $1} END { print SUM }')"
-    # target amount (bought)
-    DIP_TARGET_AMOUNT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".bought 2>/dev/null | tail -1 | awk '{ print $4 }' | awk '{ printf "%." '$DECIMAL_LIMIT' "f\n", int($0 * 10^'$DECIMAL_LIMIT') / 10^'$DECIMAL_LIMIT' }')"
+    # if percentage of total orders has not reached 100%, if not greater than 100, if DCA
+    if [[ "$DIP_LEFTOVER_TOTAL_CHECK" -lt "101" || "$(grep -c "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".dca || true)" -gt "0" ]] &>/dev/null; then
 
-    # if zero, equals zero
-    if [[ -z "$DIP_LEFTOVER_FILLED_AMOUNT" || "$DIP_LEFTOVER_FILLED_AMOUNT" -eq "0" ]] &>/dev/null; then
-      DIP_LEFTOVER_FILLED_AMOUNT="0"
-    fi
+      # amount of order filled (sold)
+      DIP_LEFTOVER_FILLED_AMOUNT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".selling 2>/dev/null | awk '{ SUM += $1} END { print SUM }')"
+      # target amount (bought)
+      DIP_TARGET_AMOUNT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".bought 2>/dev/null | tail -1 | awk '{ print $4 }' | awk '{ printf "%." '$DECIMAL_LIMIT' "f\n", int($0 * 10^'$DECIMAL_LIMIT') / 10^'$DECIMAL_LIMIT' }')"
 
-    # calculate total filled
-    DIP_LEFTOVER_FILLED=$(awk "BEGIN { result = 100 / $DIP_TARGET_AMOUNT * $DIP_LEFTOVER_FILLED_AMOUNT; printf \"%.9f\", (result > 100 ? 100 : result) }" 2>/dev/null | awk '{ printf "%.4f\n", $1 }')
-
-    # if zero
-    if [[ -z "$DIP_LEFTOVER_FILLED" || "$DIP_LEFTOVER_FILLED" == "0.0000" ]] &>/dev/null; then
-      DIP_LEFTOVER_FILLED="0"
-    fi
-
-    # if leftover filled greater or equal to n
-    if [[ "$(echo "$DIP_LEFTOVER_FILLED" | awk -F. '{ print $1 }')" -gt "99" || "$DIP_LEFTOVER_FILLED" > "99" ]] &>/dev/null; then
-      DIP_LEFTOVER_FILLED="100"
-    fi
-
-    # re calculate receive amount based on order size
-    DIP_SELL_AMOUNT_REFERENCE="$(echo "$(echo "$DIP_LEFTOVER_SIZE/100" | bc -l 2>/dev/null)*$DIP_GET_AMOUNT_REFERENCE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
-    # re calculate profit amount based on order size
-    DIP_SELL_AMOUNT_PROFIT="$(echo "$(echo "$DIP_LEFTOVER_SIZE/100" | bc -l 2>/dev/null)*$DIP_GET_AMOUNT_PROFIT" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
-
-    # if order has no losses (negative symbol), is not 100
-    if [[ "$(echo "$DIP_SELL_AMOUNT_PROFIT" | grep -c "-" || true)" -eq "0" && ! "$DIP_LEFTOVER_FILLED" == "100" ]] &>/dev/null; then
-
-      ##########################################################################
-
-      log_date
-
-      ##########################################################################
-      ##########################################################################
-
-      # if xeggex order
-      if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
-        # CreateOrder limit ####################################################
-        PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "sell" "limit" "$LISTING_BALANCE" "$DIP_TARGET_ASK" "false")"
-        # debug line ###########################################################
-        echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY sell limit $LISTING_BALANCE $DIP_TARGET_ASK false <--- Selling asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
-        ########################################################################
-        sleep 1
+      # if zero, equals zero
+      if [[ -z "$DIP_LEFTOVER_FILLED_AMOUNT" || "$DIP_LEFTOVER_FILLED_AMOUNT" -eq "0" ]] &>/dev/null; then
+        DIP_LEFTOVER_FILLED_AMOUNT="0"
       fi
 
-      ##########################################################################
-      ##########################################################################
+      # calculate total filled
+      DIP_LEFTOVER_FILLED=$(awk "BEGIN { result = 100 / $DIP_TARGET_AMOUNT * $DIP_LEFTOVER_FILLED_AMOUNT; printf \"%.9f\", (result > 100 ? 100 : result) }" 2>/dev/null | awk '{ printf "%.4f\n", $1 }')
 
-      tx_id
+      # if zero
+      if [[ -z "$DIP_LEFTOVER_FILLED" || "$DIP_LEFTOVER_FILLED" == "0.0000" ]] &>/dev/null; then
+        DIP_LEFTOVER_FILLED="0"
+      fi
 
-      # selling output (log)
-      DIP_SELL_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Sell $LISTING_BALANCE $LISTING_CURRENCY for $DIP_SELL_AMOUNT_REFERENCE $REFERENCE_CURRENCY"
-      echo "$DIP_SELL_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
-      # filled output (log)
-      DIP_FILLED_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Sell ${DIP_LEFTOVER_SIZE_OUTPUT:?}% Selling: ${DIP_LEFTOVER_TOTAL:?}% Filled: ${DIP_LEFTOVER_FILLED:?}%"
-      echo "$DIP_FILLED_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
-      # profit output (log)
-      DIP_SELL_PROFIT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Gains: $DIP_SELL_AMOUNT_PROFIT $REFERENCE_CURRENCY -> ${DIP_GET_RATIO_PROFIT:?}%"
-      echo "$DIP_SELL_PROFIT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+      # if leftover filled greater or equal to n
+      if [[ "$(echo "$DIP_LEFTOVER_FILLED" | awk -F. '{ print $1 }')" -gt "99" || "$DIP_LEFTOVER_FILLED" > "99" ]] &>/dev/null; then
+        DIP_LEFTOVER_FILLED="100"
+      fi
 
-      # it was selling
-      DIP_SELLING="1"
+      # re calculate receive amount based on order size
+      DIP_SELL_AMOUNT_REFERENCE="$(echo "$(echo "$DIP_LEFTOVER_SIZE/100" | bc -l 2>/dev/null)*$DIP_GET_AMOUNT_REFERENCE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
+      # re calculate profit amount based on order size
+      DIP_SELL_AMOUNT_PROFIT="$(echo "$(echo "$DIP_LEFTOVER_SIZE/100" | bc -l 2>/dev/null)*$DIP_GET_AMOUNT_PROFIT" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
+
+      # if order has no losses (negative symbol), is not 100
+      if [[ "$(echo "$DIP_SELL_AMOUNT_PROFIT" | grep -c "-" || true)" -eq "0" && ! "$DIP_LEFTOVER_FILLED" == "100" ]] &>/dev/null; then
+
+        ########################################################################
+
+        log_date
+
+        ########################################################################
+        ########################################################################
+
+        # if xeggex order
+        if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
+          # CreateOrder limit ##################################################
+          PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "sell" "limit" "$LISTING_BALANCE" "$DIP_TARGET_ASK" "false")"
+          # debug line #########################################################
+          echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY sell limit $LISTING_BALANCE $DIP_TARGET_ASK false <--- Selling asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
+          ######################################################################
+          sleep 1
+        fi
+
+        ########################################################################
+        ########################################################################
+
+        tx_id
+
+        # selling output (log)
+        DIP_SELL_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Sell $LISTING_BALANCE $LISTING_CURRENCY for $DIP_SELL_AMOUNT_REFERENCE $REFERENCE_CURRENCY"
+        echo "$DIP_SELL_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+        # filled output (log)
+        DIP_FILLED_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Sell ${DIP_LEFTOVER_SIZE_OUTPUT:?}% Selling: ${DIP_LEFTOVER_TOTAL:?}% Filled: ${DIP_LEFTOVER_FILLED:?}%"
+        echo "$DIP_FILLED_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+        # profit output (log)
+        DIP_SELL_PROFIT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Gains: $DIP_SELL_AMOUNT_PROFIT $REFERENCE_CURRENCY -> ${DIP_GET_RATIO_PROFIT:?}%"
+        echo "$DIP_SELL_PROFIT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+
+        # it was selling
+        DIP_SELLING="1"
+      fi
     fi
   fi
 fi
