Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -3329,6 +3329,22 @@ if [[ "$DIP_DUST" == "1" ]] &>/dev/null; then
 
   ##############################################################################
 
+  # default
+  DIP_SELL_FAILED="0"
+
+  # if market fail at selling (null)
+  if [[ "$(cat "${SYS_DIR:?}"/robot/*.null 2>/dev/null | grep -c "$DIP_CHANGE_NAME/$DIP_REFERENCE_NAME" || true)" -gt "0" ]] &>/dev/null; then
+    # sell failed (dusting)
+    DIP_SELL_FAILED="1"
+    # if any data
+    if [[ "$(grep -wc "$DIP_CHANGE_NAME" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders || true)" -gt "0" ]] &>/dev/null; then
+      # remove failed order (orders)
+      echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null | grep -v "$DIP_CHANGE_NAME/$DIP_REFERENCE_NAME")" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders
+    fi
+  fi
+
+  ##############################################################################
+
   # old ask price (trades)
   DIP_CHANGE_OLD_PRICE_TRADES="$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$DIP_CHANGE_NAME"_"$DIP_REFERENCE_NAME".trades 2>/dev/null | grep "buy" | head -10 | awk '{ print $5 }' | sed '/^$/d' | awk '{ SUM += $1} END { print SUM }' | awk '{ printf "%.9f\n", $1 }')"
   # old ask price count (max 10)
@@ -3417,8 +3433,8 @@ if [[ "$DIP_DUST" == "1" ]] &>/dev/null; then
     fi
   fi
 
-  # not already spent
-  if [[ "$DIP_CHANGE_ALREADY_SPENT" -eq "0" ]] &>/dev/null; then
+  # not already spent and did not already fail
+  if [[ "$DIP_CHANGE_ALREADY_SPENT" -eq "0" && "$DIP_SELL_FAILED" == "0" ]] &>/dev/null; then
     # if dust is old enough (43200 seconds = 1/2 day), or just dust regardless if no bought file
     if [[ "$DIP_BOUGHT_FILE_AGE_SECONDS" -gt "43200" ]] &>/dev/null; then
       # if dust is old enough (86400 seconds = 1 day), or just dust regardless if no sold file
