Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -3333,13 +3333,21 @@ if [[ "$DIP_DUST" == "1" ]] &>/dev/null; then
   DIP_SELL_FAILED="0"
 
   # if market fail at selling (null)
-  if [[ "$(cat "${SYS_DIR:?}"/robot/*.null 2>/dev/null | grep -c "$DIP_CHANGE_NAME/$DIP_REFERENCE_NAME" || true)" -gt "0" ]] &>/dev/null; then
-    # sell failed (dusting)
-    DIP_SELL_FAILED="1"
+  if [[ "$(cat "${SYS_DIR:?}"/robot/*.dust 2>/dev/null | grep -c "$DIP_CHANGE_NAME/$DIP_REFERENCE_NAME" || true)" -gt "0" ]] &>/dev/null; then
+
+    # dust amount data
+    DIP_DUST_AMOUNT="$(cat "${SYS_DIR:?}"/robot/*.dust 2>/dev/null | grep "$DIP_CHANGE_NAME/$DIP_REFERENCE_NAME" | head -1 | awk '{ print $10 }' |  awk '{ printf "%." '$DECIMAL_LIMIT' "f\n", int($0 * 10^'$DECIMAL_LIMIT') / 10^'$DECIMAL_LIMIT' }')"
+
+    # data amount equals balance data
+    if [[ "$DIP_DUST_AMOUNT" == "$DIP_CHANGE_ASSET_BALANCE" ]] &>/dev/null; then
+      # sell failed (dusting)
+      DIP_SELL_FAILED="1"
+    fi
+
     # if any data
-    if [[ "$(grep -wc "$DIP_CHANGE_NAME" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders || true)" -gt "0" ]] &>/dev/null; then
+    if [[ "$(grep -wc "$DIP_CHANGE_NAME" "${SYS_DIR:?}"/robot/orders || true)" -gt "0" ]] &>/dev/null; then
       # remove failed order (orders)
-      echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null | grep -v "$DIP_CHANGE_NAME/$DIP_REFERENCE_NAME")" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders
+      echo "$(cat "${SYS_DIR:?}"/robot/orders 2>/dev/null | grep -v "$DIP_CHANGE_NAME/$DIP_REFERENCE_NAME")" >"${SYS_DIR:?}"/robot/orders
     fi
   fi
 
