Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -1299,73 +1299,76 @@ if [[ "$DIP_MARKET_FILE_AGE" -gt "$DIP_MAX_AGE" ]] &>/dev/null; then
             # active listing dca count (market list)
             DIP_ACTIVE_LISTING_DCA="$(cat "${SYS_DIR:?}"/robot/*.market.list 2>/dev/null | grep -wc "$LISTING_CURRENCY" 2>/dev/null || true)"
 
-            # if listing is single inside active
-            if [[ "$DIP_ACTIVE_LISTING_DCA" -eq "1" ]] &>/dev/null; then
+            # if DCA has been checked already
+            if [[ "$(tail -100 "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null | grep -c "Has balance!" || true)" -eq "0" ]] &>/dev/null; then
+              # if listing is single inside active
+              if [[ "$DIP_ACTIVE_LISTING_DCA" -eq "1" ]] &>/dev/null; then
 
-              # ruled by configuration
-              DIP_DCA_RAW="$DIP_DCA"
-              # calculate dca value
-              DIP_DCA_NUM="$(echo "$DIP_DCA/100" | bc -l 2>/dev/null)"
-              # include old balance, ruled by configuration (dollar cost average)
-              DIP_BUY_AMOUNT_LISTING_DCA="$(echo "$DIP_DCA_NUM*$LISTING_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%."'$DIP_DECIMAL_LIMIT'"f\n", $1 }')"
+                # ruled by configuration
+                DIP_DCA_RAW="$DIP_DCA"
+                # calculate dca value
+                DIP_DCA_NUM="$(echo "$DIP_DCA/100" | bc -l 2>/dev/null)"
+                # include old balance, ruled by configuration (dollar cost average)
+                DIP_BUY_AMOUNT_LISTING_DCA="$(echo "$DIP_DCA_NUM*$LISTING_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%."'$DIP_DECIMAL_LIMIT'"f\n", $1 }')"
 
-              log_date
+                log_date
 
-              # order count (buy)
-              DIP_ORDER_BUY="$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders | grep -w "$LISTING_CURRENCY" | grep -c "buy" || true)"
-              # order count (sell)
-              DIP_ORDER_SELL="$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders | grep -w "$LISTING_CURRENCY" | grep -c "sell" || true)"
+                # order count (buy)
+                DIP_ORDER_BUY="$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders | grep -w "$LISTING_CURRENCY" | grep -c "buy" || true)"
+                # order count (sell)
+                DIP_ORDER_SELL="$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders | grep -w "$LISTING_CURRENCY" | grep -c "sell" || true)"
 
-              # if zero
-              if [[ -z "$DIP_ORDER_BUY" ]] &>/dev/null; then
-                DIP_ORDER_BUY="0"
-              fi
+                # if zero
+                if [[ -z "$DIP_ORDER_BUY" ]] &>/dev/null; then
+                  DIP_ORDER_BUY="0"
+                fi
 
-              # if zero
-              if [[ -z "$DIP_ORDER_SELL" ]] &>/dev/null; then
-                DIP_ORDER_SELL="0"
-              fi
+                # if zero
+                if [[ -z "$DIP_ORDER_SELL" ]] &>/dev/null; then
+                  DIP_ORDER_SELL="0"
+                fi
 
-              # log dca balance output
-              DIP_TARGET_DCA_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: DCA: $LISTING_CURRENCY Has balance! $LISTING_BALANCE $LISTING_CURRENCY (${DIP_ORDER_BUY:?}b/${DIP_ORDER_SELL:?}s)"
-              echo "$DIP_TARGET_DCA_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+                # log dca balance output
+                DIP_TARGET_DCA_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: DCA: $LISTING_CURRENCY Has balance! $LISTING_BALANCE $LISTING_CURRENCY (${DIP_ORDER_BUY:?}b/${DIP_ORDER_SELL:?}s)"
+                echo "$DIP_TARGET_DCA_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
 
-              # log dca data output
-              DIP_TARGET_DCA_I_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: DCA: +Target amount ${DIP_DCA_RAW:?}% -> +$DIP_BUY_AMOUNT_LISTING_DCA $LISTING_CURRENCY"
-              echo "$DIP_TARGET_DCA_I_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+                # log dca data output
+                DIP_TARGET_DCA_I_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: DCA: +Target amount ${DIP_DCA_RAW:?}% -> +$DIP_BUY_AMOUNT_LISTING_DCA $LISTING_CURRENCY"
+                echo "$DIP_TARGET_DCA_I_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
 
-              # reset order
-              DIP_DCA_ORDER_ID="$(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders | grep "$REFERENCE_CURRENCY" | awk '{ print $1 }' | tr -d ':' | head -1)"
-              # cancel order
-              cancelOrder "$DIP_DCA_ORDER_ID" 2>>"${LOG_ERROR:?}"
+                # reset order
+                DIP_DCA_ORDER_ID="$(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders | grep "$REFERENCE_CURRENCY" | awk '{ print $1 }' | tr -d ':' | head -1)"
+                # cancel order
+                cancelOrder "$DIP_DCA_ORDER_ID" 2>>"${LOG_ERROR:?}"
 
-              # if any valued data
-              if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY:?}"_"${REFERENCE_CURRENCY:?}".sold | egrep -c "[0-9]+" || true)" -gt "0" ]] &>/dev/null; then
-                # reset sold file (reset data, age)
-                truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY:?}"_"${REFERENCE_CURRENCY:?}".sold &>/dev/null
-              fi
+                # if any valued data
+                if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY:?}"_"${REFERENCE_CURRENCY:?}".sold | egrep -c "[0-9]+" || true)" -gt "0" ]] &>/dev/null; then
+                  # reset sold file (reset data, age)
+                  truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY:?}"_"${REFERENCE_CURRENCY:?}".sold &>/dev/null
+                fi
 
-              # remove old dca order
-              remove_old_dca
+                # remove old dca order
+                remove_old_dca
 
-              ##################################################################
-              ##################################################################
+                ################################################################
+                ################################################################
 
-              # create/update dca list
-              echo "$LISTING_CURRENCY/$REFERENCE_CURRENCY Deposited: $LISTING_BALANCE_DEPOSITED $LISTING_CURRENCY DCA: ${DIP_DCA_RAW:?}% Extra: +$DIP_BUY_AMOUNT_LISTING_DCA $LISTING_CURRENCY $(date | xargs)" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".dca
+                # create/update dca list
+                echo "$LISTING_CURRENCY/$REFERENCE_CURRENCY Deposited: $LISTING_BALANCE_DEPOSITED $LISTING_CURRENCY DCA: ${DIP_DCA_RAW:?}% Extra: +$DIP_BUY_AMOUNT_LISTING_DCA $LISTING_CURRENCY $(date | xargs)" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".dca
 
-              ##################################################################
-              ##################################################################
+                ################################################################
+                ################################################################
 
-            else
+              else
 
-              # log potential dca data output
-              DIP_TARGET_DCA_NO_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: DCA Potential: $LISTING_BALANCE $LISTING_CURRENCY on $DIP_ACTIVE_LISTING_DCA active markets."
-              echo "$DIP_TARGET_DCA_NO_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
-              # if no_dca market data
-              if [[ "$(grep -c "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".no_dca || true)" -gt "0" ]] &>/dev/null; then
-                # reset no_dca market
-                echo "$(grep -v "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".no_dca 2>/dev/null)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".no_dca
+                # log potential dca data output
+                DIP_TARGET_DCA_NO_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: DCA Potential: $LISTING_BALANCE $LISTING_CURRENCY on $DIP_ACTIVE_LISTING_DCA active markets."
+                echo "$DIP_TARGET_DCA_NO_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+                # if no_dca market data
+                if [[ "$(grep -c "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".no_dca || true)" -gt "0" ]] &>/dev/null; then
+                  # reset no_dca market
+                  echo "$(grep -v "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".no_dca 2>/dev/null)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".no_dca
+                fi
               fi
             fi
           fi
