Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -3398,127 +3398,129 @@ if [[ -n "$DIP_TARGET_BOUGHT_DATA" ]] &>/dev/null; then
   if [[ "$DIP_ACTIVE_TARGET" -eq "1" ]] &>/dev/null; then
     # if target has not already sold
     if [[ "$(grep "$LISTING_CURRENCY/$DIP_MARKETS" "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log | egrep "Buy |Sell |Sold" | tail -1 | grep -c "Sold" || true)" -eq "0" ]] &>/dev/null; then
-
       # if data
       if [[ -n "$LISTING_CURRENCY" && -n "$DIP_MARKETS" ]] &>/dev/null; then
         # if no orders exist
         if [[ "$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders* 2>/dev/null | grep -w "$LISTING_CURRENCY" | grep -wc "$DIP_MARKETS" || true)" -eq "0" ]] &>/dev/null; then
-          # if not a new buy
-          if [[ "$BUY_TRADES_STATUS" -eq "0" ]] &>/dev/null; then
-            # if not recently selling
-            if [[ "$LOG_SELLING_STATUS" -eq "0" ]] &>/dev/null; then
+          # if no orders exist
+          if [[ "$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$LISTING_CURRENCY"_"$DIP_MARKETS".orders 2>/dev/null | grep -w "$LISTING_CURRENCY" | grep -wc "$DIP_MARKETS" || true)" -eq "0" ]] &>/dev/null; then
+            # if not a new buy
+            if [[ "$BUY_TRADES_STATUS" -eq "0" ]] &>/dev/null; then
+              # if not recently selling
+              if [[ "$LOG_SELLING_STATUS" -eq "0" ]] &>/dev/null; then
 
-              ##################################################################
-              # fully sold order
-              ##################################################################
+                ################################################################
+                # fully sold order
+                ################################################################
 
-              # total sum check (confirmed sold)
-              DIP_TOTAL_SOLD_FILE_CHECK="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".sold 2>/dev/null | awk '{ SUM += $1} END { print SUM }' | awk '{ printf "%." '$DECIMAL_LIMIT_FLICKER' "f\n", int($0 * 10^'$DECIMAL_LIMIT_FLICKER') / 10^'$DECIMAL_LIMIT_FLICKER' }' | tr -d '.' | sed 's/^0*//')"
-
-              # if zero
-              if [[ -z "$DIP_TOTAL_SOLD_FILE_CHECK" ]] &>/dev/null; then
                 # total sum check (confirmed sold)
-                DIP_TOTAL_SOLD_FILE_CHECK="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".selling 2>/dev/null | awk '{ SUM += $1} END { print SUM }' | awk '{ printf "%." '$DECIMAL_LIMIT_FLICKER' "f\n", int($0 * 10^'$DECIMAL_LIMIT_FLICKER') / 10^'$DECIMAL_LIMIT_FLICKER' }' | tr -d '.' | sed 's/^0*//')"
-              fi
+                DIP_TOTAL_SOLD_FILE_CHECK="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".sold 2>/dev/null | awk '{ SUM += $1} END { print SUM }' | awk '{ printf "%." '$DECIMAL_LIMIT_FLICKER' "f\n", int($0 * 10^'$DECIMAL_LIMIT_FLICKER') / 10^'$DECIMAL_LIMIT_FLICKER' }' | tr -d '.' | sed 's/^0*//')"
 
-              # target bought amount check
-              TARGET_BOUGHT_CHECK="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".bought | tail -1 | awk '{ print $4 }' | awk '{ printf "%." '$DECIMAL_LIMIT_FLICKER' "f\n", int($0 * 10^'$DECIMAL_LIMIT_FLICKER') / 10^'$DECIMAL_LIMIT_FLICKER' }' | tr -d '.' | sed 's/^0*//')"
+                # if zero
+                if [[ -z "$DIP_TOTAL_SOLD_FILE_CHECK" ]] &>/dev/null; then
+                  # total sum check (confirmed sold)
+                  DIP_TOTAL_SOLD_FILE_CHECK="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".selling 2>/dev/null | awk '{ SUM += $1} END { print SUM }' | awk '{ printf "%." '$DECIMAL_LIMIT_FLICKER' "f\n", int($0 * 10^'$DECIMAL_LIMIT_FLICKER') / 10^'$DECIMAL_LIMIT_FLICKER' }' | tr -d '.' | sed 's/^0*//')"
+                fi
 
-              ##################################################################
-
-              # if total sum greater or equal than target
-              if [[ "$DIP_TOTAL_SOLD_FILE_CHECK" -ge "$TARGET_BOUGHT_CHECK" ]] &>/dev/null; then
-
-                log_date
+                # target bought amount check
+                TARGET_BOUGHT_CHECK="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".bought | tail -1 | awk '{ print $4 }' | awk '{ printf "%." '$DECIMAL_LIMIT_FLICKER' "f\n", int($0 * 10^'$DECIMAL_LIMIT_FLICKER') / 10^'$DECIMAL_LIMIT_FLICKER' }' | tr -d '.' | sed 's/^0*//')"
 
                 ################################################################
 
-                # if zero
-                if [[ -z "$DIP_GET_AMOUNT_PROFIT" || -z "$DIP_GET_RATIO_PROFIT" ]] &>/dev/null; then
-                  # if bought data exist
-                  if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".bought 2>/dev/null | sed '/^$/d' | wc -l)" -gt "0" ]] &>/dev/null; then
-                    # use original percentage value from bought data
-                    DIP_GET_RATIO_PROFIT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".bought 2>/dev/null | tail -1 | sed '/^$/d' | awk '{ print $NF }' | tr -d '%')"
-                    # use original get amount value from bought data
-                    DIP_GET_AMOUNT_PROFIT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".bought 2>/dev/null | tail -1 | sed '/^$/d' | awk '{ print $22 }')"
+                # if total sum greater or equal than target
+                if [[ "$DIP_TOTAL_SOLD_FILE_CHECK" -ge "$TARGET_BOUGHT_CHECK" ]] &>/dev/null; then
+
+                  log_date
+
+                  ##############################################################
+
+                  # if zero
+                  if [[ -z "$DIP_GET_AMOUNT_PROFIT" || -z "$DIP_GET_RATIO_PROFIT" ]] &>/dev/null; then
+                    # if bought data exist
+                    if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".bought 2>/dev/null | sed '/^$/d' | wc -l)" -gt "0" ]] &>/dev/null; then
+                      # use original percentage value from bought data
+                      DIP_GET_RATIO_PROFIT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".bought 2>/dev/null | tail -1 | sed '/^$/d' | awk '{ print $NF }' | tr -d '%')"
+                      # use original get amount value from bought data
+                      DIP_GET_AMOUNT_PROFIT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".bought 2>/dev/null | tail -1 | sed '/^$/d' | awk '{ print $22 }')"
+                    fi
                   fi
-                fi
 
-                # if zero
-                if [[ -z "$DIP_GET_RATIO_PROFIT" ]] &>/dev/null; then
-                  DIP_GET_RATIO_PROFIT="0.00"
-                fi
+                  # if zero
+                  if [[ -z "$DIP_GET_RATIO_PROFIT" ]] &>/dev/null; then
+                    DIP_GET_RATIO_PROFIT="0.00"
+                  fi
 
-                # if zero
-                if [[ -z "$DIP_GET_AMOUNT_PROFIT" ]] &>/dev/null; then
-                  DIP_GET_AMOUNT_PROFIT="0.000000000"
-                fi
+                  # if zero
+                  if [[ -z "$DIP_GET_AMOUNT_PROFIT" ]] &>/dev/null; then
+                    DIP_GET_AMOUNT_PROFIT="0.000000000"
+                  fi
 
-                # if zero
-                if [[ -z "$DIP_BOUGHT_FILE_AGE" ]] &>/dev/null; then
-                  DIP_BOUGHT_FILE_AGE="N/A"
-                fi
+                  # if zero
+                  if [[ -z "$DIP_BOUGHT_FILE_AGE" ]] &>/dev/null; then
+                    DIP_BOUGHT_FILE_AGE="N/A"
+                  fi
 
-                ################################################################
+                  ##############################################################
 
-                # sell output (trade history)
-                DIP_LIMIT_POSITION="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : sell :: $LISTING_CURRENCY/$DIP_MARKETS :: $LISTING_BALANCE $REFERENCE_BALANCE ${DIP_GET_RATIO_PROFIT:?}% $DIP_BOUGHT_FILE_AGE"
-                echo "$DIP_LIMIT_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"
-                # cleanup output (log)
-                DIP_CLEANUP_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$DIP_MARKETS :: Removing order from pool. (Sold) Age: $DIP_BOUGHT_AGE_OUTPUT"
-                echo "$DIP_CLEANUP_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
-                # profit output (log)
-                DIP_SOLD_PROFIT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$DIP_MARKETS :: Profit: $DIP_GET_AMOUNT_PROFIT $DIP_MARKETS ${DIP_GET_RATIO_PROFIT:?}% after $DIP_BOUGHT_AGE_OUTPUT_AFTER"
-                echo "$DIP_SOLD_PROFIT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+                  # sell output (trade history)
+                  DIP_LIMIT_POSITION="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : sell :: $LISTING_CURRENCY/$DIP_MARKETS :: $LISTING_BALANCE $REFERENCE_BALANCE ${DIP_GET_RATIO_PROFIT:?}% $DIP_BOUGHT_FILE_AGE"
+                  echo "$DIP_LIMIT_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"
+                  # cleanup output (log)
+                  DIP_CLEANUP_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$DIP_MARKETS :: Removing order from pool. (Sold) Age: $DIP_BOUGHT_AGE_OUTPUT"
+                  echo "$DIP_CLEANUP_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+                  # profit output (log)
+                  DIP_SOLD_PROFIT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$DIP_MARKETS :: Profit: $DIP_GET_AMOUNT_PROFIT $DIP_MARKETS ${DIP_GET_RATIO_PROFIT:?}% after $DIP_BOUGHT_AGE_OUTPUT_AFTER"
+                  echo "$DIP_SOLD_PROFIT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
 
-                # track profit
-                echo "$LOG_DATE : $LISTING_CURRENCY/$DIP_MARKETS > $DIP_GET_AMOUNT_PROFIT $DIP_MARKETS ${DIP_GET_RATIO_PROFIT:?}% $DIP_BOUGHT_AGE_OUTPUT_AFTER" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit 2>>"${LOG_ERROR:?}"
-                # column file
-                echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit 2>/dev/null | column -t)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit
+                  # track profit
+                  echo "$LOG_DATE : $LISTING_CURRENCY/$DIP_MARKETS > $DIP_GET_AMOUNT_PROFIT $DIP_MARKETS ${DIP_GET_RATIO_PROFIT:?}% $DIP_BOUGHT_AGE_OUTPUT_AFTER" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit 2>>"${LOG_ERROR:?}"
+                  # column file
+                  echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit 2>/dev/null | column -t)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit
 
-                # remove duplicates
-                echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}" | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"
-                # reset sold file (reset data, age)
-                truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".sold &>/dev/null
-                # reset selling file (reset data)
-                truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".selling &>/dev/null
-                # reset sell_id file (reset data)
-                truncate -s 0 "${SYS_DIR:?}"/robot/"${BASENAME_STRATEGY}"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".sell_id &>/dev/null
+                  # remove duplicates
+                  echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}" | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"
+                  # reset sold file (reset data, age)
+                  truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".sold &>/dev/null
+                  # reset selling file (reset data)
+                  truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".selling &>/dev/null
+                  # reset sell_id file (reset data)
+                  truncate -s 0 "${SYS_DIR:?}"/robot/"${BASENAME_STRATEGY}"/"${LISTING_CURRENCY}"_"${DIP_MARKETS}".sell_id &>/dev/null
 
-                # reset active
-                reset_active_market_list
+                  # reset active
+                  reset_active_market_list
 
-                # if any trade data
-                if [[ -f "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"${LISTING_CURRENCY:?}"_"${DIP_MARKETS:?}".trades ]] &>/dev/null; then
+                  # if any trade data
+                  if [[ -f "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"${LISTING_CURRENCY:?}"_"${DIP_MARKETS:?}".trades ]] &>/dev/null; then
 
-                  function get_trades_data {
-                    # get trades data
-                    LISTING_TRADES=$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"${LISTING_CURRENCY:?}"_"${DIP_MARKETS:?}".trades 2>/dev/null)
-                    # extract last buy order ID from trades file
-                    BUY_TRADES_ID=$(echo "$LISTING_TRADES" | grep "buy" | head -1 | awk '{ print $1 }' | tr -d ':')
-                  }
+                    function get_trades_data {
+                      # get trades data
+                      LISTING_TRADES=$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"${LISTING_CURRENCY:?}"_"${DIP_MARKETS:?}".trades 2>/dev/null)
+                      # extract last buy order ID from trades file
+                      BUY_TRADES_ID=$(echo "$LISTING_TRADES" | grep "buy" | head -1 | awk '{ print $1 }' | tr -d ':')
+                    }
 
-                  # trades data
-                  get_trades_data
-
-                  # if no data
-                  if [[ -z "$BUY_TRADES_ID" ]] &>/dev/null; then
-                    # update trades data
-                    target_order_status
                     # trades data
                     get_trades_data
+
+                    # if no data
+                    if [[ -z "$BUY_TRADES_ID" ]] &>/dev/null; then
+                      # update trades data
+                      target_order_status
+                      # trades data
+                      get_trades_data
+                    fi
+
+                    # keep old buy id after it was sold
+                    echo "$BUY_TRADES_ID" >"${SYS_DIR:?}"/robot/"${BASENAME_STRATEGY}"/"${LISTING_CURRENCY:?}"_"${DIP_MARKETS:?}".buy_id
                   fi
 
-                  # keep old buy id after it was sold
-                  echo "$BUY_TRADES_ID" >"${SYS_DIR:?}"/robot/"${BASENAME_STRATEGY}"/"${LISTING_CURRENCY:?}"_"${DIP_MARKETS:?}".buy_id
+                  # it was sold
+                  DIP_SOLD="1"
+                  # it was removed
+                  DIP_REMOVED="1"
+                  # status
+                  DIP_BS_STATUS="Sold"
                 fi
-
-                # it was sold
-                DIP_SOLD="1"
-                # it was removed
-                DIP_REMOVED="1"
-                # status
-                DIP_BS_STATUS="Sold"
               fi
             fi
           fi
