Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -320,6 +320,19 @@ function amount_to_buy_sell() {
 
   ##############################################################################
 
+  # account allocated (n%)
+  REFERENCE_ALLOCATED="$DIP_ALLOCATED"
+
+  # if zero, use n%
+  if [[ -z "$REFERENCE_ALLOCATED" ]] &>/dev/null; then
+    REFERENCE_ALLOCATED="1" # n%
+  fi
+
+  # calculate dip allocated (configuration)
+  REFERENCE_ALLOCATED="$(echo "$REFERENCE_ALLOCATED/100" | bc -l 2>/dev/null)"
+
+  ##############################################################################
+
   # listing balance (available)
   LISTING_BALANCE="$(grep -w "\<$LISTING_CURRENCY:" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/balances 2>/dev/null | awk '{ printf "%." '$DECIMAL_LIMIT' "f\n", int($3 * 10^'$DECIMAL_LIMIT') / 10^'$DECIMAL_LIMIT' }' | head -1)"
   # reference balance (available)
@@ -903,175 +916,8 @@ fi
 
 ################################################################################
 ################################################################################
-# allocated funds & specific target & specific active variables
+# specific target & specific active variables
 ################################################################################
-################################################################################
-
-function target_profit() {
-
-  # cat profit
-  DIP_CAT_PROFIT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit 2>/dev/null || true)"
-
-  # if any data
-  if [[ -n "$DIP_CAT_PROFIT" ]] &>/dev/null; then
-
-    # original reference allocated
-    DIP_ALLOCATED_ORIGINAL="$(egrep "DIP_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }' | awk '{ printf "%.2f\n", $1 }')"
-    # if high risk
-    if [[ "$IS_HIGH_RISK" == "true" ]] &>/dev/null; then
-      # half-life, regardless (risky market)
-      DIP_ALLOCATED_ORIGINAL="$(echo "$DIP_ALLOCATED_ORIGINAL/2" | bc 2>/dev/null | awk -F. '{ print $1 }')"
-    fi
-
-    ############################################################################
-
-    # generate above list, fetch profits that took less than a day to complete, no losses
-    echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit 2>/dev/null | egrep -v "[0-9]+d| -" | awk '{ print $3 }' | sort | uniq -c | awk '{print $2, $1}' | sort -n -k 2 | tac)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".above
-
-    # if any data
-    if [[ -n "$LISTING_CURRENCY" && -n "$DIP_MARKETS" ]] &>/dev/null; then
-      # efficient market (fast)
-      EFFICIENT_MARKET="$(grep "$LISTING_CURRENCY/$DIP_MARKETS" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".above 2>/dev/null | awk '{ print $2 }')"
-    fi
-
-    # if zero
-    if [[ -z "$EFFICIENT_MARKET" ]] &>/dev/null; then
-      EFFICIENT_MARKET="0"
-    fi
-
-    ############################################################################
-
-    # generate below list, fetch profits that took more than a day to complete, losses
-    echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit 2>/dev/null | egrep "[0-9]+d| -" | awk '{ print $3 }' | sort | uniq -c | awk '{print $2, $1}' | sort -n -k 2)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".below
-
-    # if any data
-    if [[ -n "$LISTING_CURRENCY" && -n "$DIP_MARKETS" ]] &>/dev/null; then
-      # ineffective market (slow)
-      INEFFECTIVE_MARKET="$(grep "$LISTING_CURRENCY/$DIP_MARKETS" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".below | awk '{ print $2 }')"
-    fi
-
-    # if zero
-    if [[ -z "$INEFFECTIVE_MARKET" ]] &>/dev/null; then
-      INEFFECTIVE_MARKET="0"
-    fi
-
-    ############################################################################
-
-    # calculate market virtual (RAW)
-    EFFICIENT_MARKET_CALCULATED="$(echo "$EFFICIENT_MARKET-$INEFFECTIVE_MARKET" | bc -l 2>/dev/null | awk -F. '{ print $1 }')"
-
-    # if less than n, is zero
-    if [[ "$EFFICIENT_MARKET_CALCULATED" -lt "0" || "$EFFICIENT_MARKET_CALCULATED" -eq "0" ]] &>/dev/null; then
-      EFFICIENT_MARKET_CALCULATED="0"
-      # reference allocated decreased (first buy)
-      DIP_ALLOCATED="0.05"
-    fi
-
-    ############################################################################
-
-    # if data
-    if [[ -n "$LISTING_CURRENCY" || -n "$DIP_MARKETS" ]] &>/dev/null; then
-
-      # cleanup below file (wrong reference side)
-      echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".above 2>/dev/null | egrep -v "$DIP_MARKETS/")" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".above
-
-      # if above (fast profits)
-      if [[ "$(grep -c "$LISTING_CURRENCY/$DIP_MARKETS" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".above || true)" -eq "1" ]] &>/dev/null; then
-
-        # if efficient market are greater than n
-        if [[ "$EFFICIENT_MARKET_CALCULATED" -gt "0" ]] &>/dev/null; then
-
-          ######################################################################
-          ######################################################################
-
-          # calculate market virtual
-          EFFICIENT_MARKET_VIRTUAL="$(echo "$EFFICIENT_MARKET_CALCULATED/100" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
-          # calculate new allocated based on profit data
-          EFFICIENT_MARKET_DATA="$(echo "$DIP_ALLOCATED*$EFFICIENT_MARKET_VIRTUAL" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
-          # recalculate efficient market limit
-          EFFICIENT_MARKET_LIMIT="$(echo "77.7*$EFFICIENT_MARKET_DATA-$(echo "$EFFICIENT_MARKET_CALCULATED/100" | bc -l 2>/dev/null)+$(echo "$INEFFECTIVE_MARKET/50" | bc -l 2>/dev/null)" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
-          # reference allocated increased
-          DIP_ALLOCATED="$(echo "$EFFICIENT_MARKET_LIMIT+$DIP_ALLOCATED" | bc -l 2>/dev/null | awk '{ printf "%.4f\n", $1 }')"
-
-          ######################################################################
-
-          # max allocate (ruled by configuration)
-          if [[ "$(echo "$DIP_ALLOCATED" | awk '{ printf "%.2f\n", $1 }' | tr -d '.' | sed 's/^0*//')" -gt "$(echo "$DIP_MAX_ALLOCATED" | awk '{ printf "%.2f\n", $1 }' | tr -d '.' | sed 's/^0*//')" ]] &>/dev/null; then
-            # use max allowed (ruled by configuration)
-            DIP_ALLOCATED="$DIP_MAX_ALLOCATED"
-          fi
-
-          ######################################################################
-          ######################################################################
-
-          # total market data combined
-          DIP_TOTAL_MARKET_DATA="$(echo "$EFFICIENT_MARKET_CALCULATED+$INEFFECTIVE_MARKET" | bc 2>/dev/null)"
-
-          # market above output (log)
-          DIP_FAST_PROFIT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$DIP_MARKETS :: Market above: x$DIP_TOTAL_MARKET_DATA - x${INEFFECTIVE_MARKET:?} = x${EFFICIENT_MARKET_CALCULATED:?} : Increased from ${DIP_ALLOCATED_ORIGINAL:?}% to ${DIP_ALLOCATED:?}%"
-
-          # if extra logs are set
-          if [[ "$DIP_EXTRA_LOGS" == "true" ]] &>/dev/null; then
-            echo "$DIP_FAST_PROFIT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
-          else
-            echo "$DIP_FAST_PROFIT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".ssr 2>>"${LOG_ERROR:?}"
-          fi
-        fi
-      fi
-    fi
-
-    ############################################################################
-
-    # if data
-    if [[ -n "$LISTING_CURRENCY" || -n "$DIP_MARKETS" ]] &>/dev/null; then
-
-      # if non existing (no profits yet)
-      if [[ "$(grep -c "$LISTING_CURRENCY/$DIP_MARKETS" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".above || true)" -eq "0" ]] &>/dev/null; then
-        if [[ "$(grep -c "$LISTING_CURRENCY/$DIP_MARKETS" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".below || true)" -eq "0" ]] &>/dev/null; then
-
-          # reference allocated decreased (first buy)
-          DIP_ALLOCATED="0.05"
-
-          # if equal values
-          if [[ "$DIP_ALLOCATED_ORIGINAL" == "$DIP_ALLOCATED" ]] &>/dev/null; then
-            DIP_ALLOCATED_OUTPUT="Equals at ${DIP_ALLOCATED_ORIGINAL:?}% - ${DIP_ALLOCATED:?}%"
-          else
-            # not equal
-            DIP_ALLOCATED_OUTPUT="Decreased from ${DIP_ALLOCATED_ORIGINAL:?}% to ${DIP_ALLOCATED:?}%"
-          fi
-
-          # market first output (log)
-          DIP_NEW_PROFIT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$DIP_MARKETS :: Market first: x0 : $DIP_ALLOCATED_OUTPUT"
-
-          # if extra logs are set
-          if [[ "$DIP_EXTRA_LOGS" == "true" ]] &>/dev/null; then
-            echo "$DIP_NEW_PROFIT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
-          else
-            echo "$DIP_NEW_PROFIT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".ssr 2>>"${LOG_ERROR:?}"
-          fi
-        fi
-      fi
-    fi
-    # if any data
-    if [[ -n "$LISTING_CURRENCY" ]] &>/dev/null; then
-      # listing info
-      listing_info
-      # delisting status
-      isDelisting
-      # isHighRisk status
-      isHighRisk
-    fi
-    # account allocated (n%)
-    REFERENCE_ALLOCATED="$DIP_ALLOCATED"
-    # if zero, use n%
-    if [[ -z "$REFERENCE_ALLOCATED" ]] &>/dev/null; then
-      REFERENCE_ALLOCATED="1" # n%
-    fi
-    # calculate dip allocated (configuration)
-    REFERENCE_ALLOCATED="$(echo "$REFERENCE_ALLOCATED/100" | bc -l 2>/dev/null)"
-  fi
-}
-
 ################################################################################
 
 # target data for both target and active
@@ -1209,6 +1055,31 @@ function target_data() {
 
   ##############################################################################
 
+  # if any data
+  if [[ -n "$LISTING_CURRENCY" ]] &>/dev/null; then
+    # listing info
+    listing_info
+    # delisting status
+    isDelisting
+    # isHighRisk status
+    isHighRisk
+  fi
+
+  ##############################################################################
+
+  # original reference allocated
+  DIP_ALLOCATED_ORIGINAL="$(egrep "DIP_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }' | awk '{ printf "%.2f\n", $1 }')"
+
+  ##############################################################################
+
+  # if high risk
+  if [[ "$IS_HIGH_RISK" == "true" ]] &>/dev/null; then
+    # half-life, regardless (risky market)
+    DIP_ALLOCATED_ORIGINAL="$(echo "$DIP_ALLOCATED_ORIGINAL/2" | bc 2>/dev/null | awk -F. '{ print $1 }')"
+  fi
+
+  ##############################################################################
+
   # if zero
   if [[ -z "$DIP_EXTRA_LOGS" ]] &>/dev/null; then
     DIP_EXTRA_LOGS="false"
@@ -1270,6 +1141,148 @@ function target_data() {
     # if identical buy and sell prices
     if [[ "$DIP_TARGET_ASK_IDE_CHECK" == "$DIP_TARGET_BUY_IDE_CHECK" ]] &>/dev/null; then
       DIP_TARGET_SELL_STATUS="[o0]"
+    fi
+  fi
+}
+
+################################################################################
+
+function target_profit() {
+
+  # cat profit
+  DIP_CAT_PROFIT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit 2>/dev/null || true)"
+
+  # if any data
+  if [[ -n "$DIP_CAT_PROFIT" ]] &>/dev/null; then
+
+    ############################################################################
+
+    # generate above list, fetch profits that took less than a day to complete, no losses
+    echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit 2>/dev/null | egrep -v "[0-9]+d| -" | awk '{ print $3 }' | sort | uniq -c | awk '{print $2, $1}' | sort -n -k 2 | tac)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".above
+
+    # if any data
+    if [[ -n "$LISTING_CURRENCY" && -n "$DIP_MARKETS" ]] &>/dev/null; then
+      # efficient market (fast)
+      EFFICIENT_MARKET="$(grep "$LISTING_CURRENCY/$DIP_MARKETS" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".above 2>/dev/null | awk '{ print $2 }')"
+    fi
+
+    # if zero
+    if [[ -z "$EFFICIENT_MARKET" ]] &>/dev/null; then
+      EFFICIENT_MARKET="0"
+    fi
+
+    ############################################################################
+
+    # generate below list, fetch profits that took more than a day to complete, losses
+    echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit 2>/dev/null | egrep "[0-9]+d| -" | awk '{ print $3 }' | sort | uniq -c | awk '{print $2, $1}' | sort -n -k 2)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".below
+
+    # if any data
+    if [[ -n "$LISTING_CURRENCY" && -n "$DIP_MARKETS" ]] &>/dev/null; then
+      # ineffective market (slow)
+      INEFFECTIVE_MARKET="$(grep "$LISTING_CURRENCY/$DIP_MARKETS" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".below | awk '{ print $2 }')"
+    fi
+
+    # if zero
+    if [[ -z "$INEFFECTIVE_MARKET" ]] &>/dev/null; then
+      INEFFECTIVE_MARKET="0"
+    fi
+
+    ############################################################################
+
+    # calculate market virtual (RAW)
+    EFFICIENT_MARKET_CALCULATED="$(echo "$EFFICIENT_MARKET-$INEFFECTIVE_MARKET" | bc -l 2>/dev/null | awk -F. '{ print $1 }')"
+
+    # if less than n, is zero
+    if [[ "$EFFICIENT_MARKET_CALCULATED" -lt "0" || "$EFFICIENT_MARKET_CALCULATED" -eq "0" ]] &>/dev/null; then
+      EFFICIENT_MARKET_CALCULATED="0"
+      # reference allocated decreased (first buy)
+      DIP_ALLOCATED="0.05"
+    fi
+
+    ############################################################################
+
+    # if data
+    if [[ -n "$LISTING_CURRENCY" || -n "$DIP_MARKETS" ]] &>/dev/null; then
+
+      # cleanup below file (wrong reference side)
+      echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".above 2>/dev/null | egrep -v "$DIP_MARKETS/")" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".above
+
+      # if above (fast profits)
+      if [[ "$(grep -c "$LISTING_CURRENCY/$DIP_MARKETS" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".above || true)" -eq "1" ]] &>/dev/null; then
+
+        # if efficient market are greater than n
+        if [[ "$EFFICIENT_MARKET_CALCULATED" -gt "0" ]] &>/dev/null; then
+
+          ######################################################################
+          ######################################################################
+
+          # calculate market virtual
+          EFFICIENT_MARKET_VIRTUAL="$(echo "$EFFICIENT_MARKET_CALCULATED/100" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
+          # calculate new allocated based on profit data
+          EFFICIENT_MARKET_DATA="$(echo "$DIP_ALLOCATED*$EFFICIENT_MARKET_VIRTUAL" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
+          # recalculate efficient market limit
+          EFFICIENT_MARKET_LIMIT="$(echo "77.7*$EFFICIENT_MARKET_DATA-$(echo "$EFFICIENT_MARKET_CALCULATED/100" | bc -l 2>/dev/null)+$(echo "$INEFFECTIVE_MARKET/50" | bc -l 2>/dev/null)" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
+          # reference allocated increased
+          DIP_ALLOCATED="$(echo "$EFFICIENT_MARKET_LIMIT+$DIP_ALLOCATED" | bc -l 2>/dev/null | awk '{ printf "%.4f\n", $1 }')"
+
+          ######################################################################
+
+          # max allocate (ruled by configuration)
+          if [[ "$(echo "$DIP_ALLOCATED" | awk '{ printf "%.2f\n", $1 }' | tr -d '.' | sed 's/^0*//')" -gt "$(echo "$DIP_MAX_ALLOCATED" | awk '{ printf "%.2f\n", $1 }' | tr -d '.' | sed 's/^0*//')" ]] &>/dev/null; then
+            # use max allowed (ruled by configuration)
+            DIP_ALLOCATED="$DIP_MAX_ALLOCATED"
+          fi
+
+          ######################################################################
+          ######################################################################
+
+          # total market data combined
+          DIP_TOTAL_MARKET_DATA="$(echo "$EFFICIENT_MARKET_CALCULATED+$INEFFECTIVE_MARKET" | bc 2>/dev/null)"
+
+          # market above output (log)
+          DIP_FAST_PROFIT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$DIP_MARKETS :: Market above: x$DIP_TOTAL_MARKET_DATA - x${INEFFECTIVE_MARKET:?} = x${EFFICIENT_MARKET_CALCULATED:?} : Increased from ${DIP_ALLOCATED_ORIGINAL:?}% to ${DIP_ALLOCATED:?}%"
+
+          # if extra logs are set
+          if [[ "$DIP_EXTRA_LOGS" == "true" ]] &>/dev/null; then
+            echo "$DIP_FAST_PROFIT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+          else
+            echo "$DIP_FAST_PROFIT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".ssr 2>>"${LOG_ERROR:?}"
+          fi
+        fi
+      fi
+    fi
+
+    ############################################################################
+
+    # if data
+    if [[ -n "$LISTING_CURRENCY" || -n "$DIP_MARKETS" ]] &>/dev/null; then
+
+      # if non existing (no profits yet)
+      if [[ "$(grep -c "$LISTING_CURRENCY/$DIP_MARKETS" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".above || true)" -eq "0" ]] &>/dev/null; then
+        if [[ "$(grep -c "$LISTING_CURRENCY/$DIP_MARKETS" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".below || true)" -eq "0" ]] &>/dev/null; then
+
+          # reference allocated decreased (first buy)
+          DIP_ALLOCATED="0.05"
+
+          # if equal values
+          if [[ "$DIP_ALLOCATED_ORIGINAL" == "$DIP_ALLOCATED" ]] &>/dev/null; then
+            DIP_ALLOCATED_OUTPUT="Equals at ${DIP_ALLOCATED_ORIGINAL:?}% - ${DIP_ALLOCATED:?}%"
+          else
+            # not equal
+            DIP_ALLOCATED_OUTPUT="Decreased from ${DIP_ALLOCATED_ORIGINAL:?}% to ${DIP_ALLOCATED:?}%"
+          fi
+
+          # market first output (log)
+          DIP_NEW_PROFIT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$DIP_MARKETS :: Market first: x0 : $DIP_ALLOCATED_OUTPUT"
+
+          # if extra logs are set
+          if [[ "$DIP_EXTRA_LOGS" == "true" ]] &>/dev/null; then
+            echo "$DIP_NEW_PROFIT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+          else
+            echo "$DIP_NEW_PROFIT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".ssr 2>>"${LOG_ERROR:?}"
+          fi
+        fi
+      fi
     fi
   fi
 }
