Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -2038,11 +2038,14 @@ fi
 
 ################################################################################
 
+# default
+ERROR_STATUS=0
+
 # if profit found
-if [[ -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit ]] &>/dev/null; then
+if [[ -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit ]]; then
 
   # input data from the specified file
-  DATA=$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit | tr -d '%')
+  DATA=$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit | tr -d '%' 2>/dev/null || ERROR_STATUS=$?)
 
   # initialize associative arrays to store the total SUM and total percentage for each reference
   declare -A REFERENCE_TOTAL
@@ -2061,13 +2064,13 @@ if [[ -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit ]] &>/dev/null; then
     # check if the amount is numeric
     if [[ $AMOUNT =~ ^[0-9.]+$ ]] &>/dev/null; then
       # add the amount to the reference total
-      REFERENCE_TOTAL["$REFERENCE"]=$(awk "BEGIN { printf \"%.9f\", ${REFERENCE_TOTAL["$REFERENCE"]} + $AMOUNT }")
+      REFERENCE_TOTAL["$REFERENCE"]=$(awk "BEGIN { printf \"%.9f\", ${REFERENCE_TOTAL["$REFERENCE"]} + $AMOUNT }" 2>/dev/null || ERROR_STATUS=$?)
       # add the percentage to the reference total percentage
-      REFERENCE_TOTAL_PERCENTAGE["$REFERENCE"]=$(awk "BEGIN { printf \"%.2f\", ${REFERENCE_TOTAL_PERCENTAGE["$REFERENCE"]} + $PERCENTAGE }")
+      REFERENCE_TOTAL_PERCENTAGE["$REFERENCE"]=$(awk "BEGIN { printf \"%.2f\", ${REFERENCE_TOTAL_PERCENTAGE["$REFERENCE"]} + $PERCENTAGE }" 2>/dev/null || ERROR_STATUS=$?)
       # increment the count for the reference
       ((REFERENCE_COUNT["$REFERENCE"]++))
     fi
-  done <<<"$DATA"
+  done <<<"$DATA" 2>/dev/null || ERROR_STATUS=$?
 
   # output the total value and average percentage for each reference
   for REFERENCE in "${!REFERENCE_TOTAL[@]}"; do
@@ -2081,6 +2084,9 @@ if [[ -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit ]] &>/dev/null; then
   # total gains by reference, remove duplicates, sort by n
   echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".gains 2>/dev/null | awk '!a[$1]++' | sort -n -k 3 | column -t)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".gains
 fi
+
+# restore the error status and exit with it
+exit $ERROR_STATUS
 
 ################################################################################
 
