Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -2991,6 +2991,8 @@ if [[ "$DIP_TARGET_SPREAD_STATUS" == "[N0]" ]] &>/dev/null; then
 
   # bought file age (seconds)
   DIP_BOUGHT_FILE_AGE_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".bought 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
+  # trades file age (seconds)
+  DIP_TRADES_FILE_AGE_SECONDS="$(stat -c '%Y' "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".trades 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
   # sold file age (seconds)
   DIP_SOLD_FILE_AGE_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".sold 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
 
@@ -2999,19 +3001,22 @@ if [[ "$DIP_TARGET_SPREAD_STATUS" == "[N0]" ]] &>/dev/null; then
 
   # if bought is old enough (3600 seconds = 1 hour)
   if [[ "$DIP_BOUGHT_FILE_AGE_SECONDS" -gt "3600" ]] &>/dev/null; then
-    # if sold is old enough (10800 seconds = 3 hours)
-    if [[ "$DIP_SOLD_FILE_AGE_SECONDS" -gt "10800" ]] &>/dev/null; then
+    # if trades is old enough (7200 seconds = 2 hours)
+    if [[ "$DIP_TRADES_FILE_AGE_SECONDS" -gt "7200" ]] &>/dev/null; then
+      # if sold is old enough (10800 seconds = 3 hours)
+      if [[ "$DIP_SOLD_FILE_AGE_SECONDS" -gt "10800" ]] &>/dev/null; then
 
-      # if selling has no data
-      if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".selling 2>/dev/null | egrep -c "[0-9]+" || true)" -eq "0" ]] &>/dev/null; then
-        # if sold has no data
-        if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".sold 2>/dev/null | egrep -c "[0-9]+" || true)" -eq "0" ]] &>/dev/null; then
-          # not good enough anymore
-          DIP_TARGET_SPREAD_STATUS="[N0]"
-          reset_active_market_list
-          # log market new spread output
-          DIP_MARKET_RESET="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $DIP_TARGET_SPREAD_STATUS Active order was removed from pool."
-          echo "$DIP_MARKET_RESET" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+        # if selling has no data
+        if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".selling 2>/dev/null | egrep -c "[0-9]+" || true)" -eq "0" ]] &>/dev/null; then
+          # if sold has no data
+          if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".sold 2>/dev/null | egrep -c "[0-9]+" || true)" -eq "0" ]] &>/dev/null; then
+            # not good enough anymore
+            DIP_TARGET_SPREAD_STATUS="[N0]"
+            reset_active_market_list
+            # log market new spread output
+            DIP_MARKET_RESET="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $DIP_TARGET_SPREAD_STATUS Active order was removed from pool."
+            echo "$DIP_MARKET_RESET" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+          fi
         fi
       fi
     fi
