Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -2637,11 +2637,56 @@ if [[ "$DIP_ACTIVE_TARGET" -eq "1" ]] &>/dev/null; then
 fi
 
 ################################################################################
-# removing broken position (broken quest)
+# reset broken quest (bought file)
 ################################################################################
 
 bought_sold_age
 time_and_profit
+
+# if older than n seconds (using max sell and buy age limit)
+if [[ "$DIP_BOUGHT_FILE_AGE_SECONDS" -gt "$DIP_MAX_BUY_AGE_SECONDS" ]] &>/dev/null; then
+  if [[ "$DIP_SOLD_FILE_AGE_SECONDS" -gt "$DIP_MAX_SELL_AGE_SECONDS" ]] &>/dev/null; then
+
+    # active check
+    DIP_CHECK_ACTIVE="$(grep -w "$LISTING_CURRENCY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active | grep -c "$REFERENCE_CURRENCY" || true)"
+    # orders check
+    DIP_CHECK_ORDERS="$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders | grep -c "$REFERENCE_CURRENCY" || true)"
+
+    # if true active, no orders
+    if [[ "$DIP_CHECK_ACTIVE" -gt "0" && "$DIP_CHECK_ORDERS" -eq "0" ]] &>/dev/null; then
+
+      # broken bought data
+      DIP_BROKEN_BOUGHT_DATA="$(cat "${SYS_DIR:?}"/robot/"${BASENAME_STRATEGY}"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".bought 2>/dev/null)"
+
+      # if any data
+      if [[ -n "$DIP_BROKEN_BOUGHT_DATA" ]] &>/dev/null; then
+
+        # broken bought price from data
+        DIP_BROKEN_BOUGHT_PRICE="$(echo "$DIP_BROKEN_BOUGHT_DATA" | tail -1 | awk '{ print $10 }' | tr -d '()')"
+        # broken selling price from data
+        DIP_BROKEN_SELLING_PRICE="$(echo "$DIP_BROKEN_BOUGHT_DATA" | tail -1 | awk '{ print $16 }' | tr -d '()')"
+        # broken bought price now
+        DIP_BROKEN_BOUGHT_PRICE_NOW="$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/prices 2>/dev/null | grep "$LISTING_CURRENCY" | grep "$REFERENCE_CURRENCY" | awk '{ print $2 }')"
+
+        # if any data
+        if [[ -n "$DIP_BROKEN_BOUGHT_PRICE" && -n "$DIP_BROKEN_SELLING_PRICE" ]] &>/dev/null; then
+          # if price has changed drastically, bought price less than price now
+          if [[ "$DIP_BROKEN_BOUGHT_PRICE" < "$DIP_BROKEN_BOUGHT_PRICE_NOW" && "$DIP_BROKEN_SELLING_PRICE" < "$DIP_BROKEN_BOUGHT_PRICE_NOW" ]] &>/dev/null; then
+            # reset broken quest data (bought file)
+            truncate -s 0 "${SYS_DIR:?}"/robot/"${BASENAME_STRATEGY}"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".bought &>/dev/null
+            # reset output (log)
+            DIP_RESET_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Reset slow order. (broken) Age: $DIP_BOUGHT_AGE_OUTPUT"
+            echo "$DIP_RESET_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+          fi
+        fi
+      fi
+    fi
+  fi
+fi
+
+################################################################################
+# removing broken quest (active target)
+################################################################################
 
 # broken buy age check x n
 DIP_MAX_BUY_AGE_SECONDS_BROKEN="$(echo "$DIP_MAX_BUY_AGE_SECONDS*5" | bc 2>/dev/null)"
@@ -2669,8 +2714,6 @@ if [[ "$DIP_BOUGHT_FILE_AGE_SECONDS" -gt "$DIP_MAX_BUY_AGE_SECONDS_BROKEN" ]] &>
       fi
 
       reset_active_market_list
-      # reset broken quest data (bought file)
-      truncate -s 0 "${SYS_DIR:?}"/robot/"${BASENAME_STRATEGY}"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".bought &>/dev/null
 
       # cleanup output (log)
       DIP_CLEANUP_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Removing order from pool. (broken) Age: $DIP_BOUGHT_AGE_OUTPUT"
