Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -2927,29 +2927,33 @@ echo "$(awk -F'[:[:space:]]+' 'NR==FNR { active[$1]; next } $1 in active' "${SYS
 # cat profit
 DIP_CAT_PROFIT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit 2>/dev/null)"
 
-# new year
-DIP_NEW_YEAR="$(date '+%Y')"
-# old year
-DIP_OLD_YEAR="$(echo "$DIP_NEW_YEAR-1" | bc 2>/dev/null)"
+# if any data
+if [[ -z "$DIP_CAT_PROFIT" ]] &>/dev/null; then
 
-# if not found
-if [[ ! -f "$SYS_DIR"/robot/year || ! "$DIP_NEW_YEAR" == "$DIP_OLD_YEAR" ]] &>/dev/null; then
-  echo "$DIP_NEW_YEAR" >"$SYS_DIR"/robot/year
-fi
+  # new year
+  DIP_NEW_YEAR="$(date '+%Y')"
+  # old year
+  DIP_OLD_YEAR="$(echo "$DIP_NEW_YEAR-1" | bc 2>/dev/null)"
 
-# if not equal
-if [[ ! "$DIP_NEW_YEAR" == "$(cat "$SYS_DIR"/robot/year 2>/dev/null)" ]] &>/dev/null; then
   # if not found
-  if [[ ! -f "$SYS_DIR"/robot/"$BASENAME_STRATEGY".revenue."$(date '+%Y')" ]] &>/dev/null; then
-    # track annual revenue
-    echo "$DIP_OLD_YEAR Profits:
+  if [[ ! -f "$SYS_DIR"/robot/year || ! "$DIP_NEW_YEAR" == "$DIP_OLD_YEAR" ]] &>/dev/null; then
+    echo "$DIP_NEW_YEAR" >"$SYS_DIR"/robot/year
+  fi
+
+  # if not equal
+  if [[ ! "$DIP_NEW_YEAR" == "$(cat "$SYS_DIR"/robot/year 2>/dev/null)" ]] &>/dev/null; then
+    # if not found
+    if [[ ! -f "$SYS_DIR"/robot/"$BASENAME_STRATEGY".revenue."$(date '+%Y')" ]] &>/dev/null; then
+      # track annual revenue
+      echo "$DIP_OLD_YEAR Profits:
 $(echo "$DIP_CAT_PROFIT" 2>/dev/null)
 
 $DIP_OLD_YEAR Gains:
 $(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".gains 2>/dev/null)" >"$SYS_DIR"/robot/"$BASENAME_STRATEGY".revenue."$(date '+%Y')"
-    # reset last year profit, gains
-    truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit &>/dev/null
-    truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".gains &>/dev/null
+      # reset last year profit, gains
+      truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit &>/dev/null
+      truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".gains &>/dev/null
+    fi
   fi
 fi
 
@@ -3268,71 +3272,74 @@ fi
 # cat profit
 DIP_CAT_PROFIT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit 2>/dev/null)"
 
-# default error status
-ERROR_STATUS=0
+# if any data
+if [[ -z "$DIP_CAT_PROFIT" ]] &>/dev/null; then
 
-# if profit found
-if [[ -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit ]] &>/dev/null; then
-  # if not empty
-  if [[ -s "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit ]] &>/dev/null; then
+  # default error status
+  ERROR_STATUS=0
 
-    # input data from the specified file
-    DATA=$(echo "$DIP_CAT_PROFIT" | tr -d '%' 2>/dev/null || ERROR_STATUS=$?)
-    # initialize associative arrays to store the total SUM and total percentage for each reference
-    declare -A REFERENCE_TOTAL
-    declare -A REFERENCE_TOTAL_PERCENTAGE
-    declare -A REFERENCE_COUNT
+  # if profit found
+  if [[ -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit ]] &>/dev/null; then
+    # if not empty
+    if [[ -s "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".profit ]] &>/dev/null; then
 
-    # loop through each line in the input data
-    while read -r LINE; do
-      # extract the reference name (the part before '>')
-      REFERENCE=$(echo "$LINE" | awk -F'>' '{print $1}' | awk -F' ' '{print $NF}' | awk -F'/' '{print $2}' | awk '{print $1}')
-      # extract the numeric value after '>'
-      AMOUNT=$(echo "$LINE" | awk -F'>' '{print $2}' | awk '{print $1}')
-      # extract the last numeric value
-      PERCENTAGE=$(echo "$LINE" | awk '{print $7}' | tr -d '%')
+      # input data from the specified file
+      DATA=$(echo "$DIP_CAT_PROFIT" | tr -d '%' 2>/dev/null || ERROR_STATUS=$?)
+      # initialize associative arrays to store the total SUM and total percentage for each reference
+      declare -A REFERENCE_TOTAL
+      declare -A REFERENCE_TOTAL_PERCENTAGE
+      declare -A REFERENCE_COUNT
 
-      # check if the amount is numeric
-      if [[ $AMOUNT =~ ^[0-9.]+$ ]] &>/dev/null; then
+      # loop through each line in the input data
+      while read -r LINE; do
+        # extract the reference name (the part before '>')
+        REFERENCE=$(echo "$LINE" | awk -F'>' '{print $1}' | awk -F' ' '{print $NF}' | awk -F'/' '{print $2}' | awk '{print $1}')
+        # extract the numeric value after '>'
+        AMOUNT=$(echo "$LINE" | awk -F'>' '{print $2}' | awk '{print $1}')
+        # extract the last numeric value
+        PERCENTAGE=$(echo "$LINE" | awk '{print $7}' | tr -d '%')
 
-        # add the amount to the reference total
-        REFERENCE_TOTAL["$REFERENCE"]=$(awk "BEGIN { printf \"%.9f\", ${REFERENCE_TOTAL["$REFERENCE"]} + $AMOUNT }" 2>/dev/null || {
-          ERROR_STATUS=$?
-          true
-        })
-        # add the percentage to the reference total percentage
-        REFERENCE_TOTAL_PERCENTAGE["$REFERENCE"]=$(awk "BEGIN { printf \"%.2f\", ${REFERENCE_TOTAL_PERCENTAGE["$REFERENCE"]} + $PERCENTAGE }" 2>/dev/null || {
-          ERROR_STATUS=$?
-          true
-        })
+        # check if the amount is numeric
+        if [[ $AMOUNT =~ ^[0-9.]+$ ]] &>/dev/null; then
 
-        # increment the count for the reference
-        ((REFERENCE_COUNT["$REFERENCE"]++))
-      fi
-    done <<<"$DATA" 2>/dev/null || {
-      ERROR_STATUS=$?
-      true
-    }
+          # add the amount to the reference total
+          REFERENCE_TOTAL["$REFERENCE"]=$(awk "BEGIN { printf \"%.9f\", ${REFERENCE_TOTAL["$REFERENCE"]} + $AMOUNT }" 2>/dev/null || {
+            ERROR_STATUS=$?
+            true
+          })
+          # add the percentage to the reference total percentage
+          REFERENCE_TOTAL_PERCENTAGE["$REFERENCE"]=$(awk "BEGIN { printf \"%.2f\", ${REFERENCE_TOTAL_PERCENTAGE["$REFERENCE"]} + $PERCENTAGE }" 2>/dev/null || {
+            ERROR_STATUS=$?
+            true
+          })
 
-    # output the total value and average percentage for each reference to a temporary gains file
-    TEMP_GAINS_FILE="${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".temp_gains
-    for REFERENCE in "${!REFERENCE_TOTAL[@]}"; do
-      TOTAL="${REFERENCE_TOTAL["$REFERENCE"]}"
-      TOTAL_PERCENTAGE="${REFERENCE_TOTAL_PERCENTAGE["$REFERENCE"]}"
-      COUNT="${REFERENCE_COUNT["$REFERENCE"]}"
-      AVERAGE_PERCENTAGE=$(awk "BEGIN { printf \"%.2f\", $TOTAL_PERCENTAGE / $COUNT }")
-      printf "%s: %s %.2f%%\n" "$REFERENCE" "$TOTAL" "$AVERAGE_PERCENTAGE" >>"$TEMP_GAINS_FILE"
-    done
+          # increment the count for the reference
+          ((REFERENCE_COUNT["$REFERENCE"]++))
+        fi
+      done <<<"$DATA" 2>/dev/null || {
+        ERROR_STATUS=$?
+        true
+      }
 
-    # remove duplicates, sort, column
-    echo "$(awk '!a[$1]++' "$TEMP_GAINS_FILE" 2>/dev/null)" | sort -n -k 2 | column -t >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".gains
-    # remove the temporary file
-    rm "$TEMP_GAINS_FILE" &>/dev/null
+      # output the total value and average percentage for each reference to a temporary gains file
+      TEMP_GAINS_FILE="${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".temp_gains
+      for REFERENCE in "${!REFERENCE_TOTAL[@]}"; do
+        TOTAL="${REFERENCE_TOTAL["$REFERENCE"]}"
+        TOTAL_PERCENTAGE="${REFERENCE_TOTAL_PERCENTAGE["$REFERENCE"]}"
+        COUNT="${REFERENCE_COUNT["$REFERENCE"]}"
+        AVERAGE_PERCENTAGE=$(awk "BEGIN { printf \"%.2f\", $TOTAL_PERCENTAGE / $COUNT }")
+        printf "%s: %s %.2f%%\n" "$REFERENCE" "$TOTAL" "$AVERAGE_PERCENTAGE" >>"$TEMP_GAINS_FILE"
+      done
+
+      # remove duplicates, sort, column
+      echo "$(awk '!a[$1]++' "$TEMP_GAINS_FILE" 2>/dev/null)" | sort -n -k 2 | column -t >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".gains
+      # remove the temporary file
+      rm "$TEMP_GAINS_FILE" &>/dev/null
+    fi
   fi
+  # default error status
+  ERROR_STATUS=0
 fi
-
-# default error status
-ERROR_STATUS=0
 
 ################################################################################
 
