Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -3320,36 +3320,39 @@ bought_sold_age
 
 # if still selling, wait
 if [[ "$(egrep -c "[0-9]+" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".selling 2>/dev/null || true)" -eq "0" ]] &>/dev/null; then
-  # if any data, not selling
-  if [[ -n "$DIP_BOUGHT_FILE_AGE_SECONDS" && -n "$DIP_SOLD_FILE_AGE_SECONDS" && "$DIP_SELLING" == "0" ]] &>/dev/null; then
-    # if older than n seconds
-    if [[ "$DIP_BOUGHT_FILE_AGE_SECONDS" -gt "$DIP_MAX_BUY_AGE_SECONDS" ]] &>/dev/null; then
-      if [[ "$DIP_SOLD_FILE_AGE_SECONDS" -gt "$(echo "$DIP_MAX_BUY_AGE_SECONDS+3600" | bc -l 2>/dev/null | awk '{ printf "%.0f\n", $1 }')" ]] &>/dev/null; then
-        # data exist
-        if [[ -n "$LISTING_CURRENCY" && -n "$REFERENCE_CURRENCY" ]] &>/dev/null; then
-          # if specific market does not exist in orders file
-          if [[ "$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null | grep -w "$REFERENCE_CURRENCY" | egrep -c "sell|buy" || true)" -eq "0" ]] &>/dev/null; then
-            # if specific market does exist in active file
-            if [[ "$(grep -c "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null || true)" -eq "1" ]] &>/dev/null; then
+  # if sold, wait
+  if [[ "$(egrep -c "[0-9]+" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".sold 2>/dev/null || true)" -eq "0" ]] &>/dev/null; then
+    # if any data, not selling
+    if [[ -n "$DIP_BOUGHT_FILE_AGE_SECONDS" && -n "$DIP_SOLD_FILE_AGE_SECONDS" && "$DIP_SELLING" == "0" ]] &>/dev/null; then
+      # if older than n seconds
+      if [[ "$DIP_BOUGHT_FILE_AGE_SECONDS" -gt "$DIP_MAX_BUY_AGE_SECONDS" ]] &>/dev/null; then
+        if [[ "$DIP_SOLD_FILE_AGE_SECONDS" -gt "$(echo "$DIP_MAX_BUY_AGE_SECONDS+3600" | bc -l 2>/dev/null | awk '{ printf "%.0f\n", $1 }')" ]] &>/dev/null; then
+          # data exist
+          if [[ -n "$LISTING_CURRENCY" && -n "$REFERENCE_CURRENCY" ]] &>/dev/null; then
+            # if specific market does not exist in orders file
+            if [[ "$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null | grep -w "$REFERENCE_CURRENCY" | egrep -c "sell|buy" || true)" -eq "0" ]] &>/dev/null; then
+              # if specific market does exist in active file
+              if [[ "$(grep -c "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null || true)" -eq "1" ]] &>/dev/null; then
 
-              # removing active order output (log)
-              DIP_OLD_ACTIVE_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Removing order from pool. (No orders) Age: $DIP_BOUGHT_AGE_OUTPUT"
-              echo "$DIP_OLD_ACTIVE_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+                # removing active order output (log)
+                DIP_OLD_ACTIVE_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Removing order from pool. (No orders) Age: $DIP_BOUGHT_AGE_OUTPUT"
+                echo "$DIP_OLD_ACTIVE_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
 
-              # reset active
-              reset_active_market_list
+                # reset active
+                reset_active_market_list
 
-              # if any data
-              if [[ "$(grep -wc "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$BASENAME_STRATEGY".orders || true)" -gt "0" ]] &>/dev/null; then
-                # remove failed order (orders)
-                echo "$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$BASENAME_STRATEGY".orders 2>/dev/null | grep -v "$LISTING_CURRENCY/$REFERENCE_CURRENCY")" >"${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$BASENAME_STRATEGY".orders
+                # if any data
+                if [[ "$(grep -wc "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$BASENAME_STRATEGY".orders || true)" -gt "0" ]] &>/dev/null; then
+                  # remove failed order (orders)
+                  echo "$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$BASENAME_STRATEGY".orders 2>/dev/null | grep -v "$LISTING_CURRENCY/$REFERENCE_CURRENCY")" >"${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$BASENAME_STRATEGY".orders
+                fi
+
+                # pause no order market (listing)
+                echo "$LISTING_CURRENCY" | sed '/^$/d' >>"${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/pause
+
+                # it was removed
+                DIP_REMOVED="1"
               fi
-
-              # pause no order market (listing)
-              echo "$LISTING_CURRENCY" | sed '/^$/d' >>"${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/pause
-
-              # it was removed
-              DIP_REMOVED="1"
             fi
           fi
         fi
@@ -3684,36 +3687,39 @@ DIP_MAX_SELL_AGE_SECONDS_BROKEN="$(echo "$DIP_MAX_SELL_AGE_SECONDS*1.369" | bc 2
 
 # if still selling, wait
 if [[ "$(egrep -c "[0-9]+" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".selling 2>/dev/null || true)" -eq "0" ]] &>/dev/null; then
-  # if older than n seconds (using max sell and buy age limit)
-  if [[ "$DIP_BOUGHT_FILE_AGE_SECONDS" -gt "$DIP_MAX_BUY_AGE_SECONDS_BROKEN" ]] &>/dev/null; then
-    if [[ "$DIP_SOLD_FILE_AGE_SECONDS" -gt "$DIP_MAX_SELL_AGE_SECONDS_BROKEN" ]] &>/dev/null; then
+  # if sold, wait
+  if [[ "$(egrep -c "[0-9]+" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".sold 2>/dev/null || true)" -eq "0" ]] &>/dev/null; then
+    # if older than n seconds (using max sell and buy age limit)
+    if [[ "$DIP_BOUGHT_FILE_AGE_SECONDS" -gt "$DIP_MAX_BUY_AGE_SECONDS_BROKEN" ]] &>/dev/null; then
+      if [[ "$DIP_SOLD_FILE_AGE_SECONDS" -gt "$DIP_MAX_SELL_AGE_SECONDS_BROKEN" ]] &>/dev/null; then
 
-      # orders check
-      DIP_ACTIVE_BROKEN_ORDERS="$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders | grep -wc "$LISTING_CURRENCY" || true)"
+        # orders check
+        DIP_ACTIVE_BROKEN_ORDERS="$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders | grep -wc "$LISTING_CURRENCY" || true)"
 
-      # if no orders
-      if [[ "$DIP_ACTIVE_BROKEN_ORDERS" -eq "0" ]] &>/dev/null; then
+        # if no orders
+        if [[ "$DIP_ACTIVE_BROKEN_ORDERS" -eq "0" ]] &>/dev/null; then
 
-        # reset all files (reset data, age)
-        truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".* &>/dev/null
+          # reset all files (reset data, age)
+          truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".* &>/dev/null
 
-        # reset active
-        reset_active_market_list
+          # reset active
+          reset_active_market_list
 
-        # if any data
-        if [[ "$(grep -wc "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$BASENAME_STRATEGY".orders || true)" -gt "0" ]] &>/dev/null; then
-          # remove failed order (orders)
-          echo "$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$BASENAME_STRATEGY".orders 2>/dev/null | grep -v "$LISTING_CURRENCY/$REFERENCE_CURRENCY")" >"${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$BASENAME_STRATEGY".orders
+          # if any data
+          if [[ "$(grep -wc "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$BASENAME_STRATEGY".orders || true)" -gt "0" ]] &>/dev/null; then
+            # remove failed order (orders)
+            echo "$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$BASENAME_STRATEGY".orders 2>/dev/null | grep -v "$LISTING_CURRENCY/$REFERENCE_CURRENCY")" >"${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$BASENAME_STRATEGY".orders
+          fi
+
+          # cleanup output (log)
+          DIP_CLEANUP_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Removing order from pool. (failed) Age: $DIP_BOUGHT_AGE_OUTPUT"
+          echo "$DIP_CLEANUP_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+          # pause failed market (listing)
+          echo "$LISTING_CURRENCY" | sed '/^$/d' >>"${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/pause
+
+          # it was removed
+          DIP_REMOVED="1"
         fi
-
-        # cleanup output (log)
-        DIP_CLEANUP_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Removing order from pool. (failed) Age: $DIP_BOUGHT_AGE_OUTPUT"
-        echo "$DIP_CLEANUP_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
-        # pause failed market (listing)
-        echo "$LISTING_CURRENCY" | sed '/^$/d' >>"${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/pause
-
-        # it was removed
-        DIP_REMOVED="1"
       fi
     fi
   fi
