Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -998,21 +998,8 @@ function target_data() {
 
   ##############################################################################
 
-  # if zero
-  if [[ -z "$LISTING_CURRENCY" ]] &>/dev/null; then
-    # target symbol
-    DIP_TARGET_SYMBOL="$(echo "$DIP_TARGET_FILE_OUTPUT" | awk '{ print $1 }' | tr -d ':')"
-    # listing (target from above)
-    LISTING_CURRENCY="$(echo "$DIP_TARGET_SYMBOL" 2>/dev/null | awk -F/ '{ print $1 }')"
-  fi
-
-  # if zero
-  if [[ -z "$DIP_MARKETS" ]] &>/dev/null; then
-    # target symbol
-    DIP_TARGET_SYMBOL="$(echo "$DIP_TARGET_FILE_OUTPUT" | awk '{ print $1 }' | tr -d ':')"
-    # reference (market from above)
-    DIP_MARKETS="$(echo "$DIP_TARGET_SYMBOL" 2>/dev/null | awk -F/ '{ print $2 }')"
-  fi
+  # listing (target from above)
+  LISTING_CURRENCY="$(echo "$DIP_TARGET_SYMBOL" 2>/dev/null | awk -F/ '{ print $1 }')"
 
   ##############################################################################
   ##############################################################################
@@ -2190,19 +2177,21 @@ if [[ "$DIP_MARKET_FILE_AGE" -gt "$DIP_MAX_AGE" ]] &>/dev/null; then
 
     ############################################################################
 
-    # active target status
-    if [[ "$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders | grep -c "$DIP_MARKETS" || true)" -gt "0" ]] &>/dev/null; then
+    # if any data
+    if [[ -n "$LISTING_CURRENCY" && -n "$DIP_MARKETS" ]] &>/dev/null; then
+      # active target status
+      if [[ "$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders | grep -c "$DIP_MARKETS" || true)" -gt "0" ]] &>/dev/null; then
+        log_date
 
-      log_date
+        # buy order count
+        DIP_BUY_ORDER_COUNT="$(grep -w "$DIP_MARKETS" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null | grep -w "$LISTING_CURRENCY" 2>/dev/null | grep -c "buy" || true)"
+        # sell order count
+        DIP_SELL_ORDER_COUNT="$(grep -w "$DIP_MARKETS" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null | grep -w "$LISTING_CURRENCY" 2>/dev/null | grep -c "sell" || true)"
 
-      # buy order count
-      DIP_BUY_ORDER_COUNT="$(grep -w "$DIP_MARKETS" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null | grep -w "$LISTING_CURRENCY" 2>/dev/null | grep -c "buy" || true)"
-      # sell order count
-      DIP_SELL_ORDER_COUNT="$(grep -w "$DIP_MARKETS" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null | grep -w "$LISTING_CURRENCY" 2>/dev/null | grep -c "sell" || true)"
-
-      # log target output
-      DIP_MARKET_FOUND_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$DIP_MARKETS :: Active Target: $DIP_BOUGHT_AGE_OUTPUT F: ${DIP_LEFTOVER_FILLED:?}% D: $DIP_TARGET_DIP S: $DIP_TARGET_SPREAD PM: $DIP_TARGET_PRICE_MOVEMENT B/S: $DIP_BUY_ORDER_COUNT/$DIP_SELL_ORDER_COUNT"
-      echo "$DIP_MARKET_FOUND_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+        # log target output
+        DIP_MARKET_FOUND_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$DIP_MARKETS :: Active Target: $DIP_BOUGHT_AGE_OUTPUT F: ${DIP_LEFTOVER_FILLED:?}% D: $DIP_TARGET_DIP S: $DIP_TARGET_SPREAD PM: $DIP_TARGET_PRICE_MOVEMENT B/S: $DIP_BUY_ORDER_COUNT/$DIP_SELL_ORDER_COUNT"
+        echo "$DIP_MARKET_FOUND_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+      fi
     fi
 
     ############################################################################
