Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -2948,12 +2948,22 @@ fi
 
 # if sold has a signal
 if [[ "$DIP_TARGET_SPREAD_STATUS" == "[N0]" ]] &>/dev/null; then
-  # if sold has no data
-  if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".sold 2>/dev/null | egrep -c "[0-9]+" || true)" -eq "0" ]] &>/dev/null; then
-    reset_active_market_list
-    # log market new spread output
-    DIP_MARKET_RESET="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $DIP_TARGET_SPREAD_STATUS Active order was removed from pool."
-    echo "$DIP_MARKET_RESET" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+
+  # selling file age (seconds)
+  DIP_SELLING_FILE_AGE_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${DIP_CHANGE_NAME}"_"${REFERENCE_CURRENCY}".selling 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
+
+  # if selling is old enough
+  if [[ "$DIP_SELLING_FILE_AGE_SECONDS" -gt "300" ]] &>/dev/null; then
+    # if selling has no data
+    if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".selling 2>/dev/null | egrep -c "[0-9]+" || true)" -eq "0" ]] &>/dev/null; then
+      # if sold has no data
+      if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY}"_"${REFERENCE_CURRENCY}".sold 2>/dev/null | egrep -c "[0-9]+" || true)" -eq "0" ]] &>/dev/null; then
+        reset_active_market_list
+        # log market new spread output
+        DIP_MARKET_RESET="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $DIP_TARGET_SPREAD_STATUS Active order was removed from pool."
+        echo "$DIP_MARKET_RESET" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+      fi
+    fi
   fi
 fi
 
