Update

diff --git a/include/strategies/dip_strategy b/include/strategies/dip_strategy
--- a/include/strategies/dip_strategy
+++ b/include/strategies/dip_strategy
@@ -463,6 +463,21 @@ function remove_old_dca() {
 
 ################################################################################
 
+# dip today date
+DIP_TODAY_DATE="^$(date +'%d/%m')"
+
+# count skipped and selected throughout the day
+DIP_SELECT_COUNT="$(grep "$DIP_TODAY_DATE" "${LOG_DIR:?}"/leeloo/robot.DIP*log | grep "Select" | awk '!a[$7]++' | wc -l)"
+DIP_SKIP_COUNT="$(grep "$DIP_TODAY_DATE" "${LOG_DIR:?}"/leeloo/robot.DIP*log | grep "Skip" | awk '!a[$7]++' | wc -l)"
+
+# skip select count output (log)
+if [[ "$(tail -"$LOG_LENGTH" "${LOG_DIR:?}"/leeloo/robot.log | grep -c " :: Today: " || true)" -eq "0" ]] &>/dev/null; then
+  DIP_SS_COUNT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : ALL/$REFERENCE_CURRENCY :: Today: $DIP_TODAY_DATE Selected: $DIP_SELECT_COUNT Skipped: $DIP_SKIP_COUNT"
+  echo "$DIP_SS_COUNT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+fi
+
+################################################################################
+
 function cancel_DCA() {
   # if listing, reference has data
   if [[ -n "$LISTING_CURRENCY" || -n "$REFERENCE_CURRENCY" ]] &>/dev/null; then
