Update

diff --git a/include/strategies/mcs_strategy b/include/strategies/mcs_strategy
--- a/include/strategies/mcs_strategy
+++ b/include/strategies/mcs_strategy
@@ -184,11 +184,38 @@ Last_Order.txid.......: $TX_ID_LAST $TX_ID_AGE (${TX_ID_AGE_DAYS:?}d)" | column 
 open_positions
 
 ################################################################################
+# market chaser tweaker
+################################################################################
+
+# default
+MCS_MARKET_TWEAK="369"
+
+# no funds
+if [[ "$NO_FUNDS" == "1" ]] &>/dev/null; then
+  # reset market chaser limits
+  find "${LOG_DIR:?}"/leeloo/*/ -maxdepth 1 -name 'insufficient_MCS*' -exec rm {} \; &>/dev/null
+  MCS_MARKET_TWEAK_LIMIT="$(grep "MCS" "${LOG_DIR:?}"/leeloo/buy_limit)"
+  # remove limit data
+  echo "$(grep -v "MCS" "${LOG_DIR:?}"/leeloo/buy_limit)" >"${LOG_DIR:?}"/leeloo/buy_limit
+  # tweak limit
+  MCS_MARKET_TWEAK="9"
+  # tweak output
+  MARKET_MCS_TWEAK="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Reset limit $MCS_MARKET_TWEAK_LIMIT !"
+  echo "$MARKET_MCS_TWEAK" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
+fi
+
+# if listing allocated greater than 0
+if [[ "$(echo "$LISTING_ALLOCATED" | grep -c "[.]" || true)" -gt "0" ]] &>/dev/null; then
+  # listing allocated tweak
+  LISTING_ALLOCATED="${LISTING_ALLOCATED:?}${MCS_MARKET_TWEAK:?}${RANDOM_ORDER_NUMBER:?}"
+fi
+
+################################################################################
 
 # random order amount
-RANDOM_ORDER_NUMBER=$((((RANDOM % 369248369) + 1)))
+RANDOM_ORDER_NUMBER=$((((RANDOM % 36987654321) + 1)))
 # calculate new listing amount
-LISTING_AMOUNT_RANDOM="$(echo "$(echo "${LISTING_ALLOCATED:?}1${RANDOM_ORDER_NUMBER:?}/100" | bc -l 2>/dev/null)*$LISTING_AVAILABLE_BALANCE" | bc -l 2>/dev/null)"
+LISTING_AMOUNT_RANDOM="$(echo "$(echo "$LISTING_ALLOCATED/100" | bc -l 2>/dev/null)*$LISTING_AVAILABLE_BALANCE" | bc -l 2>/dev/null)"
 # new listing amount
 LISTING_AMOUNT="$(echo "$LISTING_AMOUNT_RANDOM" | awk '{ printf "%.9f\n", $1 }')"
 
